### ISSUE TITLE
refactor `vpm compile`

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1101]
- https://github.com/voedger/voedger/blob/683d4aa13a77cdbf79edc24c6c9f28e56c6b9171/cmd/vpm/internal/dm/impl_golang.go#L142
  - `-C` is not considered
- https://github.com/voedger/voedger/blob/683d4aa13a77cdbf79edc24c6c9f28e56c6b9171/cmd/vpm/compile.go#L57C1-L57C1
  - should be `<module name from go.mod>/<dir we're compile at>` instead of `testQPN`
- `sysPackage` -> `appdef.SysPackage`
- https://github.com/voedger/voedger/blob/683d4aa13a77cdbf79edc24c6c9f28e56c6b9171/cmd/vpm/compile.go#L61C1-L61C1
  - `compileTestAppSchema` -> `getDummyAppPackageAst`
- https://github.com/voedger/voedger/blob/683d4aa13a77cdbf79edc24c6c9f28e56c6b9171/cmd/vpm/const.go#L10
  - `testAppName          = "testapp"` -> `dummyAppName = "dummyApp"`
-

**Comment by anurmanov** [comment]
<img width="356" alt="Screenshot 2023-12-07 at 11 17 11" src="https://github.com/voedger/voedger/assets/38488987/48f6230a-4f57-4ea3-80f6-45de8b819c59">
go doesn't search go.mod like that. go.mod should be searched from current working dir and further up.
