### ISSUE TITLE
Eliminate some iteration closures

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1167]
## Motivation

- https://github.com/untillpro/air-perftests/blob/main/202312181900/profiles/top-heap-space.txt
```[tasklist]
### appdef:
- [x] IFields.Fields() & IFeilds.RefFields()
- [x] IField.Constraints() & IData.Constraints()
- [x] IContainers.Containers()
- [x] IUnique.Uniques()
```

**Comment by mail2nnv** [comment]
# Results

| routine | heap space | flat MB     | flat % 
|---------|:----------:|:-----------:|-------:
| istructsmem.(*keyType).Equals.func1 |[before](https://github.com/untillpro/air-perftests/blob/9242d4a597e5513d39dfa408385d8b07684bf7f8/202312181900/profiles/top-heap-space.txt#L7)| 38435442.40 |  57.24
||[after](https://github.com/untillpro/air-perftests/blob/9242d4a597e5513d39dfa408385d8b07684bf7f8/202312231900/profiles/top-heap-objects.txt#L166) |      0 |   0.00 
| istructsmem.checkNumberConstraints |[before](https://github.com/untillpro/air-perftests/blob/9242d4a597e5513d39dfa408385d8b07684bf7f8/202312181900/profiles/top-heap-space.txt#L13)|  965407.19 |   1.44
||[after](https://github.com/untillpro/air-perftests/blob/9242d4a597e5513d39dfa408385d8b07684bf7f8/202312231900/profiles/top-heap-objects.txt)|      0 |   0.00

**Comment by mail2nnv** [comment]
#1516 closes TODO: above
