### ISSUE TITLE
ctool: --dry-run

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1173]
## Requirements

- Rename `--test-mode` to `--dry-run`
- Do not modify `cluster.json`

**Comment by dmitrymolchanovky** [comment]
When executing a command with the **--dry-run** option, a folder named **dry-run** is created in the working folder. The log and the modified cluster.json are saved to the **dry-run** folder. The **cluster.json** file is in the working folder is not modified in this case.
