### ISSUE TITLE
need clear error description instead of panic in parser (nil memory dereference on parser.BuildAppDefs()) (panic on APPLICATION removed) (panic-in-parser-3)

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1193]
**Describe the bug**
`nil memory dereference` on `parser.BuildAppDefs()`

**To Reproduce**
- checkout [the branch](https://github.com/host6/voedger/tree/panic-in-parser-3)
- run [the test](https://github.com/host6/voedger/blob/0fef85900b1c037a5d8436ea7389c98b51676d43/cmd/vpm/main_test.go#L31C9-L31C9)

**Expected behavior**
I must be able to understand what I did wrong by the error message

**Comment by michael-say** [comment]
Multiple errors (I/O, semantic analysis) [ignored](https://github.com/host6/voedger/blob/0fef85900b1c037a5d8436ea7389c98b51676d43/cmd/vpm/compile.go#L93) before the attempt to build appdefs, that's the reason of panics
