### ISSUE TITLE
Avoid commit comments https://github.com/voedger/voedger/pull/965

### ISSUE THREAD

**Issue by ivvist** [voedger/voedger#1205]
- https://github.com/voedger/voedger/pull/965
- https://github.com/voedger/voedger/pull/1063

**Comment by ivvist** [comment]
Get rid of commit extra comments in pull request

**Comment by maxim-ge** [comment]
Not possible

**Comment by ivvist** [comment]
Done.
The key is "git commit -B". It resets commits history, when the new branch is created.
