### ISSUE TITLE
fix vpm tests that expecting the exact code point in error messages

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1270]
## Problem

**Now, in current architecture**
some vpm tests are expecting the exact code points like `schema2.sql:7:5`. [Example](https://github.com/voedger/voedger/actions/runs/7458758485/job/20293547707?pr=1263)

- Problem (hot): tests failed after #1256 

**Describe the solution you'd like**
update tests

**Comment by ivvist** [comment]
T
