### ISSUE TITLE
PLog shall not have "holes"

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1281]
## Requirements

- In case of any error Command Processor partition shall be restarted and recovery process shall be run

## Current CP workflow (bad)
- putPLog
  - nextPLogOffset++
- apply records
  - nextWLogOffset++ because sync projectors need the next WLogOffset
- sync projectors
- putWLog
  - has error -> nextWLogOffset++
## Solution
- any error on PutPLog, records apply, Sync Projectors, PutWLog:
  - partition is scheduled to be recovered on next command
  - recover on PutPLog failure is required to avoid holes in RecordIDs
- partition recover
  - read the whole log, determine next RecordID, PLog and WLog offsets
  - re-apply the last event (#1307)
    - re-apply records
    - execute sync projectors
    - PutWLog

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/1307
```

**Comment by host6** [comment]
current CP workflow
- putPLog
  - nextPLogOffset++
- apply records
  - nextWLogOffset++ because sync projectors need the next WLogOffset
- sync projectors
- putWLog
  - has error -> nextWLogOffset++
what to do if apply records is successful but sync projector is failed?

**Comment by host6** [comment]
any error - means error on PutPLog, records apply, PutWLog?
