### ISSUE TITLE
Estimate AmazonDB Driver implementation

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1333]
- Download
- Create table
- Insert data
- Query data

**Comment by anurmanov** [comment]
Clustering Key в касандре - это тоже что SortKey в Amazon
он и PartitionKey может быть бинарным, но разница в том, что SortKey всегда один в рамках одной таблицы, на сколько я понял в Cassandra Clustering key может быть несколько
прошариваюсь тут по  aws dynamodb
Primary Key в DynamoDB может быть либо PartitionKey, либо составной ключ  PartitionKey и SortKey

**Comment by anurmanov** [comment]
Example of how to run dynamodb in local: 
`docker run -p 8000:8000 -e AWS_REGION=eu-west-1 -e AWS_ACCESS_KEY_ID=local -e AWS_SECRET_ACCESS_KEY=local amazon/dynamodb-local`
