### ISSUE TITLE
istorage/amazondb

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1385]
### Implementation notes:
- `cCols` can not be empty in DynamoDB so `cCols` are always prefixed with `byte(0)` on write and the first byte is always dropped on read
- keyspaces are implemented as tables with names `<keyspaceName>.value`
- `DynamoDB` driver has no ability to write directly to `*data`. It allocates new memory for value on each read

**Comment by anurmanov** [comment]
There 2 methods in interface IAppStorage which get parameter data (pointer to slice of bytes). Cassandra's implementation of the interface can reuse memory from data param no reallocating new memry.
```
type IAppStorage interface {
	GetBatch(pKey []byte, items []GetBatchItem) (err error)
	Get(pKey []byte, cCols []byte, data *[]byte) (ok bool, err error)
        ...
}

```
But AWS SDK's implementation can't do like that. They used to allocate new memory for fetched data.

**Comment by host6** [comment]
- Unmarhsaler interface: https://github.com/aws/aws-sdk-go-v2/blob/main/feature/dynamodb/attributevalue/decode.go#L35
- deserializing the response: https://github.com/aws/aws-sdk-go-v2/blob/0990666d30b102580f681ff83ed41e9e0b4d70d7/service/dynamodb/deserializers.go#L3275
