### ISSUE TITLE
ctool: itest: backup/restore

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1431]
### Technical Design

- Create user keyspace
- Create table
- Write some data
  - 10 records
  - read and count - check that 10 records is writed
- Do backup
- Drop keyspace
- Do restore
- Query data and count - must be 10 records in place

**Comment by AlekseiPonomarev** [comment]
[TEST PASSED](https://github.com/voedger/voedger/actions/runs/7985571937)
