### ISSUE TITLE
examples/airs-bp: load schema and use in tests

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1475]
## Technical Design

- ParseSql => [AppDef ](https://github.com/voedger/voedger/blob/main/pkg/appdef/README.md#L0-L1)(ref. anurmanov, #1515)
- BuildState(AppDef)
- Use State in tests:  func like `exttinygo.NewValue()` shall go to state directly, without WASM engine

## Blocked By

- #1515

**Comment by host6** [comment]
closed in favor of #1945
