### ISSUE TITLE
devops: bp3: automate baseline schemas update on each successful test release

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1482]
On each successful shoot off to the Test branch:
BP3:
- checkout `main` branch
- build exec: `go build -o airs-bp airsbp3/cli/*.go`
- build the actual baseline schemas: execute `airs-bp baseline_schemas airsbp3/baseline_schemas` 
- actual baseline schemas will be written to `airsbp3/baseline_schemas` dir
- has something to commit -> commit + push to `main` branch of `airs-bp3` with message "baseline schemas update"

**Comment by ivvist** [comment]
Done. Commit with name "[devops: bp3: automate baseline schemas update on each successful test release #1482](https://github.com/untillpro/airs-bp3/commit/9a4a342d20024fe97102922973ddf5f859d94640)" should do the job.

**Comment by ivvist** [comment]
Done
