### ISSUE TITLE
iextenginewazero: example with ODoc order/order_item

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1509]
Solution
- [Example extension](https://github.com/voedger/voedger/blob/1ecdec1daf7503aba9feacf8f6aa172f83a1fdb4/pkg/iextenginewazero/_testdata/basicusage/main.go#L12)
- [BasicUsage test](https://github.com/voedger/voedger/blob/1ecdec1daf7503aba9feacf8f6aa172f83a1fdb4/pkg/iextenginewazero/impl_test.go#L37)

**Comment by michael-say** [comment]
closed with #1527
