### ISSUE TITLE
vpm compat: package local names shall not be changed

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1514]
## Requirements

```sql
IMPORT SCHEMA 'github.com/untillpro/airs-scheme/bp3' AS untill;
IMPORT SCHEMA 'github.com/untillpro/airs-bp3/packages/air';

APPLICATION airsbp (
	USE untill;
	USE air;
);
```
- `untill` shall always be an internal name for `github.com/untillpro/airs-scheme/bp3`
- `air` shall always be an internal name for `github.com/untillpro/airs-bp3/packages/air`

bp3 compat???

## Technical Design

....

**Comment by anurmanov** [comment]
I faced an unpleasant architectural problem working on this issue. The information about imports lays on the level of parser package. On other side appdefcompat package works with appdef.IAppDef. The IAppDef interface declares methods related to application data types. Imports information is not about application data types, it is about dependencies.

To see incompatibilities in imports we should compare two parser.AppSchemaAST trees.

**Comment by anurmanov** [comment]
I will solve this issue on the parser package level in stage of building AppSchemaAST
