### ISSUE TITLE
vpm: appdefcompat: use golang package loader

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1515]
## Requirements

- Do like this:
  - https://github.com/voedger/inv-go/blob/main/20240221-load-sql/loader1/loader_test.go
  - https://github.com/voedger/inv-go/tree/main/20240221-load-sql
- Provide a public method to load a synthetic AppDef from a folder (will be used by #1475)
  - Discuss with @ivvist

**Comment by anurmanov** [comment]
The second requirement makes us to move almost whole logic of the vpm compile command to some package. We got to decide which package it could be.
