### ISSUE TITLE
devops: bp3: update voedger dependency

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1546]
## Requirements

- Action 'Update voedger'
  - Commit name: `voedger: <voedger-commit-name>`
  - Do not use hash in name: https://github.com/untillpro/airs-bp3/commit/9e0a0ff9789fd641b2c839dd8455680fceebeb9f
  - Can be run manually
- Runs nightly

## Technical Design

1. New workflow update_voedger.yml  is added to repsoitory github.com/untillpro/airs-bp3.
    - The workflow updates airs-bp3 go.mod with the latest voedger version, runs airs-bp3 tests and pushes new go.mod.
    - The workflow is scheduled to run every day at 4:00 GMT
    - The workflow also can be run manually.
    - Commit name: `voedger: <voedger-commit-name>`
2. Voedger doe snot update any airs-bp3 dependencies anymore.

**Comment by ivvist** [comment]
Done
