### ISSUE TITLE
has commits after pull request -> pull request must be merged after the last successful build 

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1583]
## Pain/Problem/Motivation/Requirements

- made a pull request
- build is started
- made a commit when build is not completed yet
- second build is started
- first build is done -> merge when the second build is not completed
pain: second commit is wrong and the second build should fail but the pull request is merged because first build is successful

## Solution

commit when previos buld is in progress -> cancel the previous build and start the new

**Comment by ivvist** [comment]
Done.

**Comment by ivvist** [comment]
Done.
During checking Pull request, if new commit comes to the same PR from the same branch, previous workflows are cancelled.
