### ISSUE TITLE
appdef: States and Intents for commands and queries

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#1611]
- `IQuery` must implement `States(func(storage QName, names QNames))` (+builder)
- `ICommand` must implement `States(func(storage QName, names QNames))` and `Intents(func(storage QName, names QNames))` (+builder)

**Comment by mail2nnv** [comment]
To avoid escaping to the heap when using iterators, I also suggest adding the `StatesMap()map[QName]QNames` and `IntentsMap()map[QName]QNames` methods.

**Comment by mail2nnv** [comment]
*Question*: Is it necessary to validate storage names passed to builder, what should be known?

```golang
  type IStoragesBuilder interface {
    // # Panics:
    //   + if storage name empty
    //   + if storage name is invalid
    //   + if storage names contains invalid name(s)
    //   ? if storage names contains unknown type name(s)
    Add(storage QName, names ...QName)
  }
```

**Comment by mail2nnv** [comment]
### As a result of the meeting with @michael-say

Interface members `IState()` and `IIntents()` should be moved to ancestor type `IExtension`.
All final types (`ICommand`, `IQuery` and `IProjectors`) should inherit these members.
