### ISSUE TITLE
compat: implement check for inheritance modification

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1630]
e.g. INHERITS WDoc -> INHERITS ODoc must be denied
INHERITS workspace1 -> INHERITS workspace 2 must be denied
INHERITS workspace1 -> no INHERITS must be denied
no INHERITS -> start to INHERITS  must be allowed

**Comment by anurmanov** [comment]
The inheritance lines is not stored in IAppDef. That is why this issue can not be implemented right now.
