### ISSUE TITLE
state: low-level API for testing

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1647]
## Internals

- https://internals.voedger.io/services-dev/api-testing

**Comment by michael-say** [comment]
Test examples:

- [Basic Usage: Event, View](https://github.com/voedger/voedger/blob/d466918a151b00f54cea4dbf654786c84424bfb0/pkg/iextengine/wazero/_testdata/basicusage/main_test.go#L21)
- [Actualizer: WLog Get and Read, Secret, Http, SendMail](https://github.com/voedger/voedger/blob/d466918a151b00f54cea4dbf654786c84424bfb0/pkg/iextengine/wazero/_testdata/tests/main_test.go#L23)
- [Command: CommandContext, Record, RequestSubject, Result](https://github.com/voedger/voedger/blob/d466918a151b00f54cea4dbf654786c84424bfb0/pkg/iextengine/wazero/_testdata/tests/main_test.go#L70)
