### ISSUE TITLE
wrong commit message if the pull request is created manually

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1661]
## Pain/Problem/Motivation/Requirements

- `qs pr` is failed (no matter why)
- the branch is created manually
- the [pull request](https://github.com/voedger/voedger/pull/1660) is created manually
  -  `Resolves ...` comment is made manually
- merged successfully but the commit message is `main` is empty:
  - `#1587 (#1660)`
  - https://github.com/voedger/voedger/commit/a9e3e615ec35eea4cf4973dc6eb430ab9034eb49

## Solution
- the pull request is made manually -> the resulting commit message should be like `<pull request title> (#<pr number>)`

**Comment by ivvist** [comment]
Made test, the commit takes a name of merged PR.
