### ISSUE TITLE
Unable to reactivate cancelled invitation

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#1704]
### Motivation
- https://dev.untill.com/projects/#!684951

### What I do
Reactivate cancelled invitation
Request /c.sys.InitiateInvitationByEMail
```json
{
    "args":{
        "Email":"untill-nbibik-t2@outlook.com",
        "EmailTemplate":"text:Hello,<br /><br />You are invited to the unTill Reseller Portal workspace "unTill AIR BV".<br />To accept the invitation and join the workspace, please visit <a href="https://reseller.dev.air.untill.com/#/resellers/invited?verification-code=${VerificationCode}&invite-id=${InviteID}&wsid=${WSID}&email=untill-nbibik-t2%40outlook.com" target="_blank" rel="noopener noreferrer">this link</a>.<br /><br />This email was sent automatically, please do not reply",
        "EmailSubject":"You are invited",
        "Roles":"air.UntillPaymentsReseller",
        "ExpireDatetime":1712843913950
    }
}
```

### What I get
Response status 400:
```json
{"sys.Error":{"HTTPStatus":400,"Message":"subject already exists"}}
```

### What I expect
`c.sys.InitiateInvitationByEmail` should [re-actiate cancelled invitation](https://github.com/heeus/heeus-design/blob/main/workspaces/invites.md#main-sequence)

**Comment by host6** [comment]
### Now
`cdoc.sys.Subject` exists by login && cdoc.sys.Invite.State in [State_ToBeJoined, State_Joined, State_ToUpdateRoles, State_ToBeCancelled, State_Cancelled, State_ToBeLeft, State_Left] -> `subject already exists` error
### Solution
`cdoc.sys.Subject` exists by login && cdoc.sys.Invite.State in [State_ToBeJoined, State_Joined, State_ToUpdateRoles, State_ToBeCancelled, State_Left] -> `subject already exists` error
