### ISSUE TITLE
parser: reference targets

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#171]
Ref. #169

**Comment by michael-say** [comment]
syntax is now [supported](https://github.com/michael-say/voedger/commit/06e1bae7ff1ee4226779a9a7f60585c9c59ac12e) by parser, waiting for #169 to build in schemas

**Comment by mail2nnv** [comment]
Reference rules:
- [ ] *General:* Target reference must be _identified_, i.e. must have `sys.ID` field. Ref to [`IDef.Kind().DefKind.HasSystemField(SystemField_ID)`](https://github.com/voedger/voedger/blob/79719a3d717c8b524990dc237d1a804e3341f33e/pkg/appdef/def-kind.go#L79)
- [ ] `ODoc` & `ORecords`:
 - may reference to any _identified_ target;
 - may be referenced only from `ODoc` & `ORecords`.
- [ ] `WDoc` & `WRecords`: 
 - may reference to `WDoc` & `WRecords`, `СDoc` & `СRecords`, `GDoc` & `GRecords`;
 - may be referenced from `ODoc` & `ORecords`, `WDoc` & `WRecords`.
- [ ] `CDoc` & `CRecords`: 
 - may reference to `СDoc` & `СRecords`, `GDoc` & `GRecords`;
 - may be referenced from `ODoc` & `ORecords`, `WDoc` & `WRecords`, `CDoc` & `CRecords`.
- [ ] `GDoc` & `GRecords`: 
 - may reference only to `GDoc` & `GRecords`;
 - may be referenced from anywhere.
