### ISSUE TITLE
voedger: istructs.IAppStructs.Uniques() => appdef.I*Doc.UniqueField()

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#173]
# Move old uniques definition from `istructsmem` to `appdef`

## Pain:

Old uniques are described in the `istructsmem` package. The view with unique user data already exists in the storage and must be maintained in parallel with the new unique data.

## Now:

The old uniques are described in `istructsmem.AppConfigType.Uniques`.
New uniques are described in `adppdef.ICDoc.Uniques()`.
The application is forced to describe the uniques in two packages.

## Solution:

1. Delete:
- [x] Interface `IUniques` from `istruct`,
- [x] `AppConfigType.Uniques` from `istructsmem`,

2. Add to `appdef`:
- [x] `ICDoc.UniqueField() IField` (+ to other interfaces that allow unique field, e.g. `ICRecord`, `IGDoc`, ...),
- [x] `ICDocBuilder.SetUniqueField(name string)` (+ to other builders that allow unique field).

3. Do not forget:
- [x] update internal package `appdef/describe` to describe unique field in JSON.

**Comment by mail2nnv** [comment]
PR: https://github.com/voedger/voedger/pull/196
