### ISSUE TITLE
records registry

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#177]
Initiated by @mail2nnv 

**Is your feature request related to a problem? Please describe.**
- Not possible to get ORecord by ID
- Integrity validation has to read the whole referenced record

**Describe the solution you'd like**

## Functional Design
- Create an index 
```sql
CREATE VIEW RecordsRegistry(
   ID ref
   QNameID int32
   WLogOffset int64,
   PRIMARY KEY ((ID))
);
```
- sync projector that will insert in the index on each new CUD
- workaround to populate the index on the first launch:
  - create the projector in async mode
  - wait the projector for run trough the whole log
  - then use the projector in sync mode only, eliminate workarounds

## Technical Design
- `--fill-records-registry` cmd line arg provided -> `p.sys.RecordsRegistryProjector` is run in async mode, sync otherwise

## Pros
- faster validation
- faster indexing of particular Doc

## Cons
- slower write for ODocs (extra index)

**Describe alternatives you've considered**

- Keep references to ORecords as  `OffsetInEvent<<48 + WLogOffset`
  - cons: hard to sync with other database (IDs mapping)
  - pros: faster ODocs writes (no extra index)

**Comment by host6** [comment]
@mail2nnv suggests:
```
PK: WSID + (RecordID >> 12)
CC: RecordID && (1 << 12 - 1)
Value: IsActive+QNameID + WLogOffset
```

**Comment by maxim-ge** [comment]
Migrated to #663
