### ISSUE TITLE
vpm init, tidy

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1791]
## Functional Design

`vpm init`

- Create `go.mod` 
  - error if exists
- Create `packages_gen.go` 
  - error if exists
  - package `main`
  - `func main(){}`
  - DO NOT EDIT
  - import voedger sys package
- Run `go mod tidy`

`vpm tidy`

- Parse vsql files
- Recreate `packages_gen.go`
- Run `go mod tidy`

`vpm orm`
- ...
- Run `go mod tidy` if `go.mod`  exists

**Comment by host6** [comment]
vpm init <module-name>? like in go?
