### ISSUE TITLE
Cherry picking, Build/Delivery, Deployment

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1813]
## Motivation

- Doing cherry picking manually is error prone
- Separate Build/Delivery and Deployment procedures
  - **Build/Delivery**:  compile sources, run tests, build a container and put it to dockerhub
  - **Deployment**:  deploy new containers to a cluster

### Configuration

- Owner: revoke access to `rc` and `release` branches from anyone but owners

### Build/Deliver repo RC (airs-bp3/airc-backoffice2/web-poetals)

**Team DevOps_release**
  - Create an issue named `rc [notes]`
  - Wait until a comment with a reference to a running action appears

**Action workflows/rc.yml**
  - Add a comment to the issue
  - Recreate the `rc` branch from the `main` branch
  - Build/Deliver (build a container and put it to dockerhub)
  - On error: Add a comment "Error occured" - issue stays open
  - On OK: Close the issue

### Deploy RC

**ivvist**
- Commit to air-release-builder (ref. README.md)

Some action updates repo `airs-config-sync` => `swarmsync` actualizes the Test cluster.

### Build & Deploy Release (morning)

**Action [air-release-builder/workflows/release.yml](https://github.com/untillpro/air-release-builder/blob/main/.github/workflows/cronetest.yml)**
- At 5:00 CET: Builds all projects and deploy them

### Cherry pick from  `main` to `rc`

**Team DevOps_release**
- Create an issue named `cprc [notes]`
  - Body: contains list of commit hashes, separated by any character
  - Wait until a comment with a reference to a running action appears
  - Watch the action
  - On error: assign the issue with error to some repo Owner (maxim-ge, michael-say, ivvist)

**Action workflows/cp.yml**
  - Add a comment to the issue
  - Merge, Build/Deliver, Deploy
  - On error: Add a comment "Error occured"
  - On OK: Close the issue

### Cherry pick from `rc` to `release`

**Team DevOps_release**
- Create an issue named `cprelease [notes]`
  - Body: contains list of commit hashes, separated by any character
  - Workflow cprelease.yml runs at 3:00 next morning, found the issue and runs checrry-pick process
  - On error: assign the issue with error to some repo Owner (maxim-ge, michael-say, ivvist)

**Action workflows/cronecprelease.yml** run at 3:00GMT every day and search issue with name 'cprelease' or runs manually
  - Add a comment to the issue
  - Merge, Build/Deliver
  - On error: Add a comment "Error occured"
  - On OK: Close the issue

## Technical design

 - wf.cp.yml: Merge commits
- wf.cp.yml: Add a comment to the issue
- wf.cp.yml: Trigger `script.cp.sh`
- script.cp.sh: Merge commits
- wf.cp.yml: Close the issue
- wf.cronecprelease.yml: runs at 3:00 and checks if issue with 'cprelease' exist and trigger script.cp.sh

```mermaid
flowchart TD
    
    repo.bp3
    repo.bo
    repo.web-portals
    issue.cprc["issue.cprc"]
    repo.ci-action
    script.cp.sh
    wf.cp.yml
    wf.cprelease.yml

    repo.ci-action --- |has| script.cp.sh

    issue.cprc ---> |triggers| wf.cp.yml
    repo.bp3 ---|has| wf.cp.yml
    repo.bo ---|has| wf.cp.yml
    repo.web-portals ---|has| wf.cp.yml
    wf.cp.yml --> |invokes| script.cp.sh  
    wf.cprelease.yml -->|checks| issue.cprelease --> |invokes| script.cp.sh  
```

## Context

- [How to check team membership](https://github.com/voedger/voedger/blob/a6fd831dcadd75b895b7577ef096627cd785c4a6/.github/workflows/integration-test.yml#L43-L64)

**Comment by ivvist** [comment]
Done
