### ISSUE TITLE
apps/sys/clusterapp c.DeployAppImage and c.RegisterApp

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1815]
- c.cluster.DeployAppImage(AppQName, image blob) - wrong, should be c.cluster.DeployAppImage(AppQName, ImageBLOBID int64) - no porblem, blob will be stored in the target app - in `cluster` in our case
  - error on non-registered app?   
  - what else should it do?
- `c.cluster.RegisterApp(descr AppDescriptor)`
  - error on exists already or error if already was registered with different parts amount?
  - manage index by `AppID`?

**Comment by host6** [comment]
- c.cluster.DeployAppImage(AppQName, image blob) - wrong, should be c.cluster.DeployAppImage(AppQName, ImageBLOBID int64) - no porblem, blob will be stored in the target app - in `cluster` in our case
  - error on non-registered app?   
  - what else should it do?
- `c.cluster.RegisterApp(descr AppDescriptor)`
  - error on exists already?
  - manage index by `AppID`?
- `cluster.c.DeployAppImage(AppQName, image blob)

**Comment by maxim-ge** [comment]
Ref. #1890
