### ISSUE TITLE
apppartsctrl: use clusterapp

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1816]
## Requirements

- Always "deploy" cluster app, do not write to `cluster` storage at this stage
- DeployApp: shall guarantee that partsCount has not been changed
  - Use `cluster.Application` storage
  - panic

**Comment by host6** [comment]
DeployApp: shall guarantee that numAppWorkspaces has not been changed?\

**Comment by maxim-ge** [comment]
apppartsctrl does not deploy builtin apps
