### ISSUE TITLE
devops: voedger is updated in bp3 wrongly

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1864]
## Pain/Problem/Motivation/Requirements

voedger dependency in bp3 is automatically updated on an incompatible one
- voedger [commit](https://github.com/voedger/voedger/commit/c82e6c2ae8cbec573a77d1e9665ce2c225927683) make it incompatible with bp3
- in bp3 [commit](https://github.com/untillpro/airs-bp3/commit/c9b5bcde04244fba0e8640ffa295b69ebfb32708) the voedger dependency is updated on an incompatible one, not checked

## Solution
do not update if tests are not passed

**Comment by ivvist** [comment]
Fixed.
