### ISSUE TITLE
appparts.IAppPartitions.GetPartitionID(AppQName, WSID)

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1868]

**Comment by mail2nnv** [comment]
**Possibly a better name**

```golang
WorkspacePartition(istructs.AppQName, istructs.WSID) istructs.PartitionID
```

**Comment by mail2nnv** [comment]
Unfortunately, I haven't found where such an identifier `AppWorkspacePartitionID` is used. Can you clarify it?

IMHO, in your case `AppWorkspace` is not a good name, it is more correct to call it `AppSystemWorkspace`.

**Comment by host6** [comment]
ok, implement `AppWorkspacePartitionID(istructs.AppQName, istructs.WSID) istructs.PartitionID` for now please

**Comment by mail2nnv** [comment]
In general, naming the method that returns `PartitionID` simply `PartitionID()` would probably be a good idea if it doesn't get any arguments. 
It is the presence of arguments that makes this name a bad idea

**Comment by mail2nnv** [comment]
```golang
type IAppPartitions interface {
	…
	// Returns partition ID for specified workspace
	//
	// # Panics:
	// 	- if application not exists
	AppWorkspacePartitionID(istructs.AppQName, istructs.WSID) istructs.PartitionID
	…
  }
```

**Comment by host6** [comment]
the first one is better

**Comment by host6** [comment]
why not `GetPartitionID()`?
