### ISSUE TITLE
parser: Scheduled Projectors shall not have intents

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1897]
- Ref. https://github.com/voedger/voedger-internals/blob/main/concepts/sch-projectors.md

**Comment by michael-say** [comment]
@maxim-ge it's already not forbidden to declare no intents:
```go
	t.Run("no intents", func(t *testing.T) {
		require := assertions(t)
		require.NoAppSchemaError(`APPLICATION test();
		ALTER WORKSPACE sys.AppWorkspaceWS (
			EXTENSION ENGINE BUILTIN (
				PROJECTOR ScheduledProjector CRON '1 0 * * *';
			);
		);`)
	})

```

**Comment by maxim-ge** [comment]
@michael-say Intents have to be forbidden for scheduled projectors

**Comment by michael-say** [comment]
I agree regarding views, but they won't be able to e.g. [send emails](https://github.com/voedger/voedger/blob/c728320dadf45d29ee84c70e41409d44c8108d6e/pkg/iextengine/wazero/_testdata/tests/main.go#L236). Is that OK?
