### ISSUE TITLE
Send an alert when the Daily Test fails

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#1951]
## Motivation

I'm always frustrated when I see [failed actions](https://github.com/voedger/voedger/actions/runs/8795133824) without any reaction.

## Functional design

When Daily Test fails github action creates an issue:

- "Daily Test failed on dd/mm/yyyy hh:ss"
- Assignees: host6
- Labels: todo/triage

## Technical design

- https://github.com/voedger/voedger/blob/main/.github/workflows/ci-full.yml#L33
- https://github.com/voedger/voedger/commit/7bdfb99e74c938b9732c0ec266b1c86af5fe75bd

**Comment by ivvist** [comment]
Done.
If workflow "Update voedger" fails, new Issue is created in repository voedger with name "Daily Test failed on dd/mm/yyyy hh:ss"
