### ISSUE TITLE
qs: do not allow `qs u` in main branch

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1980]
## Motivation

I'm always frustrated when `qs u` in the main branch successfully creates a commit with message `misc`. I have to execute dangerous `git reset --hard HEAD~1` after that

## Functional design

`qs u` in the main branch -> abort with message like `auto commit to main is not allowed` (to be designed)

## Technical design

`qs u`
- check the tracked branch of the local branch we're currently on.
- tracked branch is `remote/<any>/main` (or `remote/<any>/master` ??) - abort

**Comment by maxim-ge** [comment]
Do not understand why it is a problem. Normally I do not work with main. If I do then I really need `qs u`.

**Comment by host6** [comment]
> Do not understand why it is a problem. Normally I do not work with main. If I do then I really need `qs u`.

I did that few times accidentally thinking that I'm in a branch. This is a problem because it is difficult to eliminate the commit from `main` branch

**Comment by maxim-ge** [comment]
How is `main` different from other branches? Wrong commit to other branch is also dangerous....

**Comment by host6** [comment]
> How is `main` different from other branches? Wrong commit to other branch is also dangerous....
It is easy to fix wrong commits in my branch: revert, recreate branch etc, it is not dangerous. Wrong commit in the main - revert and pollute the main? Recreate and loose with history? make a mistake in `git reset`?
