### ISSUE TITLE
`qs pr` in the main branch does nothing

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1981]
## Motivation

I'm always frustrated when `qs pr` does nothing in the `main` branch. I'm always start to investigate thinking I've found a bug in `qs`: I'm execute `qs pr -v`, opening an issue on github etc. And only after that I'm noticing that I'm in the `main` branch -> no problems

## Functional Design

`qs pr` in the non-applicable branch -> abort with message like `unable to create a pull request on this branch. Check if you're in the right branch` (to be designed)
## Technical Design

`qs pr`
- check if we have some artefacts in the current branch that we use to create a pull request
- missing -> abort with an appropriate message

**Comment by maxim-ge** [comment]
Do not understand the motivation

**Comment by host6** [comment]
> Do not understand the motivation

I'm expecting that `qs pr` will do something: ask me if I'm agree to create pull request, write something etc, but it does nothing -> I'm think that it is a bug in `qs` and start to investigate it but it is not a bug, just lack of appropriate interaction -> I'm frustrated

**Comment by ivvist** [comment]
Done.
If you try to make 'qs pr' from branch main of your forked repo, qs shows message: 

Unable to create a pull request on branch 'main'. Use 'qs dev <branch_name>.
