### ISSUE TITLE
qs: `qs pr` does nothing if `qs dev` was made on an another PC

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1983]
## Motivation

I'm always frustrated when I'm trying to `qs pr` on my office PC after working at home and the process just finishes without any messages. I'm thinking that it is a bug in `qs`

## Functional Design

`qs dev` on any PC, then `qs pr` on any other PCs should create the pull request
- `qs dev` stores info about the issue in the remote
- `git pull` should download that info locally
- further `qs pr` should see the info to create the pull requets that was dwonloaded from the remote
  - note: the local branch is behind its remote counterpart -> abort, ask to update first
- impossible to implement -> `qs pr` should give an appropriate message

**Comment by ivvist** [comment]
Found the scenario and bug is fixed.
