### ISSUE TITLE
os.Stat everywhere: correct err handling

### ISSUE THREAD

**Issue by host6** [voedger/voedger#1991]
## Motivation

**Now, in current architecture**
to check if file exists err of `os.Stat()` is checked for ` == nil` only, e.g. [here](https://github.com/voedger/voedger/blob/c837eb484961f5dbce959b356e93d434573e831a/cmd/ctool/scripts.go#L207)

- Problem (warm): err != nil -> error suppressed

## Technical Design

use `coreutils.Exists()`

**Comment by anurmanov** [comment]
Got it.
