### ISSUE TITLE
Referential integrity check

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#20]
The integrity check is missing for values specified in command arguments

**Comment by host6** [comment]
Implemented referencial integrity check for RecordID fields in CUDs and command args

**Comment by maxim-ge** [comment]
Why bp3 is mentioned here?

**Comment by host6** [comment]
> @host6 Why bp3 is mentioned here?
Because bp3 has some work done in context of this task: integration test implemented, various tests fixed that violates the integrity etc.
