### ISSUE TITLE
refactor bootstrap

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2005]
## Requrements

- separate inernal services start, bootstrap and public endpoints starts
- try to start VVM with an app with different number of partitons or app workspaces -> panic
- prepare storages for blobber and router apps as *IAppStorage before bootstrap
- blobber and router apps are not builtin, not used as apps at all. Storages only are used

## Internals

- [clusters/bootstrap](https://github.com/voedger/voedger-internals/blob/main/concepts/clusters/bootstrap.md)

## Depends on

- #2022

**Comment by host6** [comment]
- start everything but:
  - API endpoints (router, mertics service)
  - async actualizers
- bootstrap
  - requests directly to bus?
  - implement system API endpoint on http that accepts requests from 127.0.0.1 only?
- start the rest of services

**Comment by host6** [comment]
where to initialize IAppStorage for router and blobber apps? The doc says about it in 2 places: within Bootstrap() and within sync operator that calls Bootstrap()
