### ISSUE TITLE
SqlQuery: drop app QName and WSID from query if exists

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2007]
- [pkg/sys/sqlquery/impl.go](https://github.com/voedger/voedger/blob/32314794fd814e8ed9d8e367c4e44baa573d07cf/pkg/sys/sqlquery/impl.go#L28C35-L28C45)
  - take the sql query from `ArgumentObject().AsString(field_Query)`
  - drop stuff that determines `--wsid` presense, we will not use this approach
  - consider sql query could look like this: `select ... from [appOwner.appName.][wsid.]tableQName ... `
    - has `appOwner.appName.` -> consider we want to make the select from that app, obtain and use further `IAppStructs` for that app
    - has `wsid.` -> consider we want to make the select from that wsid, obtain and use further `IWorkspace` for that wsid
  - cut off `[appOwner.appName.]`, `[wsid.]` from the query because sql parser does not understands that, see [here](https://github.com/voedger/voedger/issues/1811#issuecomment-2051643695)
  - make `sqlparser.Parse()` be called with the cleaned sql query
- update tests

**Comment by host6** [comment]
see tests: https://github.com/voedger/voedger/blob/32314794fd814e8ed9d8e367c4e44baa573d07cf/pkg/sys/it/impl_sqlquery_test.go#L502

**Comment by mail2nnv** [comment]
Try to close with PR #2031

Reopened with dept #2036
