### ISSUE TITLE
IAppStructsProvider.AppStructsByDef()

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2199]
## Requirements

- No resources (panic)
- Clarify what else is missed

**Comment by mail2nnv** [comment]
## Now:

https://github.com/voedger/voedger/blob/e5e7457950b925a390781d29f480e24563772b35/pkg/istructs/interface.go#L22

## Should be:

```go
type IAppStructsProvider interface {
  AppStructsByDef(appdef.IAppDef) (IAppStructs, error)
}
```

## Question

*How to associate `AppDef` with `AppStruct`?*

By application name?…

`AppStructs` collects `AppStruct` in a map, the key to which is the application name  (`istructs.AppQName`). So, we need to add `IAppDef.Name() AppQName`, and pass `AppQName` to the `appdef.New(AppQName)` provider. But this would create a (bad cycle) dependency for `appdef` package on `istructs` package. An acceptable solution would be to move `AppQName` to `appdef`.

## Tech design

- [ ] `AppQName`: move from `istructs` to `appdef`
- [ ] `appdef.New(AppQName)` + `appdef.AppDef.Name() AppQName`
- [ ] `istructs.IAppStructs.AppStructsByDef(appdef.IAppDef) (IAppStructs, error)`

**Comment by mail2nnv** [comment]
The task was understood and performed incorrectly. A new task #2274 was composed.
