### ISSUE TITLE
package for storage name constants

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#2208]
### Problem (cold)
Due to "import cycle" issues, it is impossible in some packages to use storage name constants declared in `state` package
example: `uniques/consts.go` 

### Solution
Move storage names from `state` to some other package

**Comment by mail2nnv** [comment]
May be to `appdef` package? 
May we want enumeration of system storage kinds?
In general, the `appdef.IStorage` type is very primitive.

**Comment by michael-say** [comment]
in terms of #2367 it is supposed to move storage implementations to `pkg/sys/storages`. Would `pkg/sys` be the correct package for the system storage names constants? @maxim-ge @mail2nnv @host6 ?

**Comment by mail2nnv** [comment]
Some constants should be declared with `appdef` types, example:
```go
package sys
…
var SysRecordsStorageName = appdef.NewQName(appdef.SysPackage, "Records")
```

This makes the new `pkg/sys` package dependent on the existing `pkg/appdef` package. If in the future we need to use some of these constants inside `appdef`, for example, for storage validation, these constants will have to be moved to `appdef` or duplicated in it. In this connection, why don't we put them in `appdef` at once?

On the other hand, when we need a constant from the `sys` package in the `appdef` package, we can move declaration to `appdef` and just leave the synonym declaration in `sys`

```go
package appdef
…
var SysRecordsStorageName = NewQName(SysPackage, "Records")

package sys
…
var SysRecordsStorageName = appdef.SysRecordsStorageName

```

**Comment by mail2nnv** [comment]
About storage validation.
Returning to the example above, `SysRecordsStorage` validation can verify that only the  of table types (GRecord, GRoc, CRecord, CDoc, WRecord, WDoc) or substitutions (AnyRecordType, AnyGDocType, AnyCDocType, AnySingletonType, etc.) are specified in QNames for this storage

**Comment by michael-say** [comment]
> Some constants should be declared with `appdef` types, example:
> ```go
> package sys
> …
> var SysRecordsStorageName = appdef.NewQName(appdef.SysPackage, "Records")
> ```

Is it good that a constant for `SysPackage` is declared in `pkg/appdef` and not in the `pkg.sys`?

By the way, it seems there's some mess:
`appdef/consts.go`:
```go
SysPackagePath = "voedger.com/packages/sys"
```

`sys/consts.go`
```go
const PackagePath = "github.com/voedger/voedger/pkg/sys"
```
