### ISSUE TITLE
IAppStructsProvider.NewAppStructs()

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2274]
## Requirements

- Instance is created per partition
  - Per partition buckets/caches (IsFunctionRateLimitsExceeded)
- No resources (panic)
- Clarify what else is missed

```golang
NewAppStructs(aqn AppQName, appDef appdef.IAppDef, cache1, cache2...) (structs IAppStructs, err error) 
```

**Comment by mail2nnv** [comment]
1. **Remove `AppQName()` from `IAppDef`.** `AppQName` is the application name defined when the application is deployed to the cluster. It is not needed (may not be present) during the application definition phase. However, the `AppQName` type definition itself can be left in this package, but the `Name() AppQName` member in the `IAppDef` interface should be removed, as should the `AppQName` parameter in the `appdef.New()` factory
2. **The new `NewAppStructs` method in the `IAppStructs` interface** should build and add a *new* `IAppStruct` to `IAppStructs`. If something is missing in the construction (tokens, buckets, something else?) - discuss and add dependencies.

**Comment by mail2nnv** [comment]
## Final design

```go
  IAppStructsProvider interface {
    // For buildin apps. 
    BuiltIn(…) (IAppStructs error)

    // For user apps
    New(…) (IAppStructs error)
```
  }
```
