### ISSUE TITLE
example/airs-bp2: test for PBillDates

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2291]
## Requirements

- Projector (FillPBillDays) builds an index (year, day) => FirstOffset, LastOffset

Test
- Create context
  - event + PBillDates records
- Test that new day is processed correctly
- Test that existing day is processed correctly

## Context
Similar to  #1945

**Comment by anurmanov** [comment]
FillPbillDates the argument is the Pbill command call event
Takes the date and time from the event and the resulting offset (WLog).
In the projector, the argument is the Pbill command call event

Ask @michael-say about how the projector extension will work with the event if this projector is "sitting" on the command
We've have to take this event from somewhere.
After pulling the offset, day and year from the event and making a NewIntent whose FQName is the view from the task
