### ISSUE TITLE
package `projectors` -> `processors\actualizers`

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#2316]
## Motivation

I have a nice idea how to improve the [quality](https://iso25000.com/index.php/en/iso-25000-standards/iso-25010) of the sources. 

- *Move* package `projectors` move to `pkg\processors\` folder
- *Rename* package `projectors` to `actualizers`

## Context

[#2287](https://github.com/voedger/voedger/issues/2287#issuecomment-2194756885)

https://github.com/voedger/voedger/tree/main/pkg/projectors
https://github.com/voedger/voedger/tree/main/pkg/processors

**Comment by maxim-ge** [comment]
Implemented somewhere else.
