### ISSUE TITLE
parser: semantic analysis for references

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#236]
Reference rules:
- ~~[ ] *General:* Target reference must be _identified_, i.e. must have `sys.ID` field. Ref to [`IDef.Kind().DefKind.HasSystemField(SystemField_ID)`](https://github.com/voedger/voedger/blob/79719a3d717c8b524990dc237d1a804e3341f33e/pkg/appdef/def-kind.go#L79)~~
It is impossible to create table without `sys.ID` field
- [x] `ODoc` & `ORecords`:
 - may reference to any _identified_ target;
 - may be referenced only from `ODoc` & `ORecords`.
- [x] `WDoc` & `WRecords`: 
 - may reference to `WDoc` & `WRecords`, `СDoc` & `СRecords`, `GDoc` & `GRecords`;
 - may be referenced from `ODoc` & `ORecords`, `WDoc` & `WRecords`.
- [x] `CDoc` & `CRecords`: 
 - may reference to `СDoc` & `СRecords`, `GDoc` & `GRecords`;
 - may be referenced from `ODoc` & `ORecords`, `WDoc` & `WRecords`, `CDoc` & `CRecords`.
- [x] if `table1` is referenced by `table2` but in SQL `table2` is declared first then parser should create `table1` first in `IAppDefBuilder`
- [x] if a field is a ref to table from another package then specify that package. If from current package then postpone the package. I.e. `ref(currency)` insetad of `ref(untill.currency)`

**Comment by host6** [comment]
Note: if some `table1` is referenced by `table2` but in SQL `table2` is declared first then parser should create table1 first in `IAppDefBuilder`
