### ISSUE TITLE
fix `error: requires go version 1.18 through 1.22, got go1.23` error

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2480]
https://github.com/voedger/voedger/actions/runs/10399122846/job/28797545098

**Comment by anurmanov** [comment]
We need to upgrade tinygo to version 0.32 to solve this problem. Now we uses version 0.31.2 - https://github.com/untillpro/ci-action/blob/c49532c3382335dc73434a755fab79b3148c1346/.github/workflows/ci_reuse_go.yml#L45

**Comment by anurmanov** [comment]
Last manually runned Daily Test succeeded after upgrading tinygo version to 0.32
