### ISSUE TITLE
fix data race in Test_partitionProcessors_deploy() (again)

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2503]
https://github.com/voedger/voedger/actions/runs/10399122846/job/28938104664

**Comment by mail2nnv** [comment]
It looks like the test was done on old sources, or the error refers to the results of an old test.

### Error context with file names and line numbers

![image](https://github.com/user-attachments/assets/5f234484-b3f9-4dee-9448-a9be7d863bd0)

### Sources

1. [impl_apppartproc_test.go:149](https://github.com/voedger/voedger/blob/849830dc8728031289969a2a9abce6618625f428/pkg/appparts/impl_apppartproc_test.go#L149)
2. [impl_app.go:165](https://github.com/voedger/voedger/blob/849830dc8728031289969a2a9abce6618625f428/pkg/appparts/impl_app.go#L165)

**Comment by host6** [comment]
https://github.com/voedger/voedger/actions/runs/10465634276
looks like the test was run on the non-actual sources. The test is passed on the next day
