### ISSUE TITLE
appparts: borrowed partition invoke should return error if unexpected processor kind

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#2504]
## Context

https://github.com/voedger/voedger/blob/a033484412a33c33b78a36e0da8e427ef1b62c73/pkg/appparts/impl_app.go#L213

## TODO

Invoke() should return error if definition type kind (query, command, sync or async projector, job) is not match borrowed processor kind.

**Comment by host6** [comment]
done in https://github.com/voedger/voedger/pull/2519
