### ISSUE TITLE
air: action to rebuild and update voedger

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2514]
## Motivation

I'm always frustrated when I'm not able to run Air with new Voedger. Voedger updated -> need to create a separate task + pull request + manage branches to make so the Air run with new Voedger

## Functional design

Github action `Update Voedger and rebuild`
- update Voedger to the latest one in `go.mod`
- CD

**Comment by maxim-ge** [comment]
@host6 What about [bp3 action: Update voedger](https://github.com/voedger/voedger/issues/1546)?

**Comment by host6** [comment]
> @host6 What about [bp3 action: Update voedger](https://github.com/voedger/voedger/issues/1546)? You can use [this action](https://github.com/untillpro/airs-bp3/actions/workflows/update_voedger.yml)

It only updates go.mod, airs-bp3 app is not rebuilt in this case. I can not see changes in dev cluster after that action.

**Comment by ivvist** [comment]
Done: Now Update voedger builds and publishes new airs-bp3
