### ISSUE TITLE
int64 => float64 => int64 problem (IRowWriter.PutNumber())

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2559]
## Motivation

- IRowWriter.PutNumber()
  - LoadObjectFromJSon
### Problematic scenario
- call `PutFromJSON(`) providing an int value greater than 2^53 will lead to data loss on converting int64->float64 e.g. [here](https://github.com/voedger/voedger/blob/d0431125a0aa7b42060fe85bf6aa21872cba4d26/pkg/istructsmem/types.go#L810)
  - https://go.dev/play/p/obQK1vJL4L4

## Technical design
- `PutNumber(float64)` -> `PutNumber(json.Number)`
  - assumming `PutNumber()` is used after json umbarshaling only
- eliminate pkg/state/utils.go: `PopulateKeys()`: not used anymore
- CP, QP: force emit `json.Number` instead of `float64` types for numbers came from the client
- implement `coreutils.JSONUnmarshal()` that will treat numbers as `json.Number` instead of `float64`
- eliminate [PopulateKeys()](https://github.com/voedger/voedger/blob/d0431125a0aa7b42060fe85bf6aa21872cba4d26/pkg/state/utils.go#L20) (not used anymore)

**Comment by host6** [comment]
```golang
decoder := json.NewDecoder([]byte(jsonData))

// Force the decoder to use json.Number instead of float64 for numbers
decoder.UseNumber()

// Unmarshal the JSON data into the map
if err := decoder.Decode(&result); err != nil {
	log.Fatalf("Error decoding JSON: %v", err)
}

// Example of accessing the unmarshalled values
fmt.Println("Decoded JSON:", result)

// Converting the number to int64 from json.Number
if num, ok := result["int_number"].(json.Number); ok {
	intNum, err := num.Int64()
	if err != nil {
		log.Fatalf("Error converting json.Number to int64: %v", err)
	}
	fmt.Printf("The integer number is: %d\n", intNum)
}
```
