### ISSUE TITLE
parser: opertion kinds in grants for queries\commands are mixed up

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2696]
see [test](https://github.com/host6/voedger/blob/e78dd135380d47c9ce27675b78ff61a23b7d8fcb/pkg/sys/it/impl_deactivateworkspace_test.go#L44):
- for queries: 
  - IsOperationAllowed(OPKind_Select) does not work
  - IsOperationAllowed(OPKind_Execute) works
- for commands:
  - IsOperationAllowed(OPKind_Insert) does not work
  - IsOperationAllowed(OPKind_Execute) works 

whereas, see [here](https://github.com/host6/voedger/blob/e78dd135380d47c9ce27675b78ff61a23b7d8fcb/pkg/registry/appws.vsql#L102):
```sql
GRANT SELECT ON ALL QUERIES WITH TAG WithoutAuthTag TO sys.Anyone;
GRANT INSERT ON ALL COMMANDS WITH TAG WithoutAuthTag TO sys.Anyone;
```

I'm expecting: 
```sql
GRANT EXECUTE ON ALL QUERIES WITH TAG WithoutAuthTag TO sys.Anyone;
GRANT EXECUTE ON ALL COMMANDS WITH TAG WithoutAuthTag TO sys.Anyone;
```
but that does not work

**Comment by michael-say** [comment]
Done with #2726
