### ISSUE TITLE
projections: Async actualizers save their position too frequently

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#271]
## Motivation

- [epic: Air Perfomance Testing](https://dev.untill.com/projects/#!633875)

## Problem

**Now, in current architecture**
Async Actualizer save their position:
- **Buffered**: every time intent buffer is full, or after flush interval (100ms)
- **Non-buffered**: after every event (even unhandled)

**Describe the solution you'd like**
Async Actualizer save their position:
- **Buffered**: 
  - every time intent buffer is full
  - after flush interval (100ms) 
- **Non-buffered**
  - after every **handled** event
  - after flush interval (100ms) 

```[tasklist]
### Tasks
```

**Comment by maxim-ge** [comment]
@michael-say 

Non-buffered: After 100 unhandled events or after 100 ms, what happens first

**Comment by michael-say** [comment]
Resolved with #284
