### ISSUE TITLE
IAppPartition may be not returned to the pool

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2734]
## Steps to reproduce the problem

1. make so engines borrow is failed here: https://github.com/voedger/voedger/blob/ba475f1ab0e8a360249ebb0223d5b18be5de0760/pkg/appparts/impl_app.go#L175

### Result
`*borrowedPartition` taken from the pool [here](https://github.com/voedger/voedger/blob/ba475f1ab0e8a360249ebb0223d5b18be5de0760/pkg/appparts/impl_app.go#L172) will not be returned to the pool

## Expected behavior

take from pool -> error -> return to the pool before return

**Comment by maxim-ge** [comment]
Why Release is necessary?
