### ISSUE TITLE
deny to create non-ref fields with kind RecordID

### ISSUE THREAD

**Issue by host6** [voedger/voedger#274]
hide DataKind_RecordID?

**Comment by maxim-ge** [comment]
@host6 can you give an example of undesirable code?

**Comment by host6** [comment]
> @host6 can you give an example of undesirable code?

- https://github.com/untillpro/airs-bp3/blob/bad4b72909cb9a83aae54aad4e17ab310048dc5b/packages/air/dashboard/provide.go#37
- https://github.com/voedger/voedger/blob/874c8cfac957166061eb2045850bc0c050320755/pkg/sys/authnz/workspace/provide.go#L81
- https://github.com/untillpro/airs-bp3/blob/bad4b72909cb9a83aae54aad4e17ab310048dc5b/packages/air/xzreports/impl_savexzreport.go#L19

**Comment by michael-say** [comment]
@host6 parser do not creates fields of type `RecordID` directly. They are only added with function `appdef.IFieldsBuilder.AddRefField` which is used for adding reference fields, to either TABLE, TYPE or VIEW definitions.

Regarding the examples provided by you for air app, it will be solved by moving definitions to SQL

**Comment by maxim-ge** [comment]
It is not important since it is not possible to make this using vSQL
