### ISSUE TITLE
looks like `GRANT ... ON ALL TABLES` does not include the workspace descriptor

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2766]
## Motivation

**Current architecture**

workspace descriptor is not included in `ON ALL TABLES`

- **Significant Problem (warm)**: need to grant\remoke on workspace descriptor in addition to `ALL TABLES`

## Technical design

`ALL TABLES` must include the workspace descriptor

**Comment by michael-say** [comment]
fixed [here](https://github.com/mail2nnv/voedger/commit/21ea960ac5198fc2758cc240c228106a35259a8e)
