### ISSUE TITLE
Nullability: Study how zero values are kept in modified fields

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#2773]
- [istructs.ICUDRow.ModifiedFields](https://github.com/maxim-ge/voedger/blob/62dee433177fffd2a07428a13027a1ead6a2ae21/pkg/istructsmem/tables-types.go#L59)

**Comment by host6** [comment]
colclusion: `ICUDRow.ModifiedFields()` does not iterate over emptied field
