### ISSUE TITLE
parser: use filters for ACLs

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#2906]
## Context

https://github.com/voedger/voedger/blob/521fe0a078467a5341b400e51cd9bdf8db36638d/pkg/parser/types.go#L707-L710

**Comment by michael-say** [comment]
@host6 looks the declaration of the sys package [has broken](https://github.com/voedger/voedger/pull/3024/checks) because there's no any query declared in the sys package having a tag `AllowedToAuthenticatedTag`. Thoughts?
