### ISSUE TITLE
IEvents.ReadPLog should use IAppStorage.Get when 1 log item is requested

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#292]
**Is your feature request related to a problem? Please describe.**
ReadPLog [always reads](https://github.com/voedger/voedger/blob/abbfd862c009e26b0e2b849642ffa7e68b18afc8/pkg/istructsmem/impl.go#L296) with `IAppStorage.Read`

**Describe the solution you'd like**
Due to performance reasons, I'd expect:
- [x] ReadPLog reads log with `IAppStorage.Get` when `toReadCount` is 1

**Comment by mail2nnv** [comment]
complette
