### ISSUE TITLE
fix roles from sys package usage

### ISSUE THREAD

**Issue by host6** [voedger/voedger#2933]
1. use voedger from https://github.com/host6/voedger/tree/2692-voedger-use-acl
2. use airs-bp3 from main
3. use `sys.Everyone` role in FiscalCloud: modify [fiscalcloud vsql](https://github.com/host6/airs-bp3/blob/e3c4876bfd776b70e57df59c8e0d28251fa4ff0a/vvmdata/apps/untill.fiscalcloud/image/pkg/github.com/untillpro/airs-bp3/apps/fiscalcloud/schema_ws_fiscalcontainer.vsql#L153): `GRANT EXECUTE ON COMMAND FiscalizeDocument TO Anyone;` -> `GRANT EXECUTE ON COMMAND FiscalizeDocument TO sys.Everyone;`
4. run `Test_FiscalCloud_Vit`
result is error `undefined role: sys.Everyone`, should be not error

**Comment by michael-say** [comment]
closed, no fix needed, was an issue in the vvmdata contents
