### ISSUE TITLE
q.sys.Modules()

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#299]
## Motivation

#271 does not improve the performance. May be we use the wrong version of the voedger?

## Technical Design

AuthNZ: None
```
        info, ok := debug.ReadBuildInfo()
	if !ok {
		fmt.Println("No build info")
		return
	}
	for _, mod := range info.Deps {
		fmt.Printf("path: %s version: %s\n", mod.Path, mod.Version)
	}
```

**Comment by host6** [comment]
currently CLI command `version` is implemented that prints the entire `BuildInfo`
