### ISSUE TITLE
ctool: install Scylla

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#32]

**Comment by maxim-ge** [comment]
- better error messages in cluster.json
- scripts must be idempotent (swarm)

**Comment by maxim-ge** [comment]
Check environment variable SSH_AGENT_PID

**Comment by dmitrymolchanovky** [comment]
ctool with the apply command deploys three scylla nodes for the SE cluster
[PR](https://github.com/voedger/voedger/pull/83)
