### ISSUE TITLE
istoragecache: preallocated buffers for keys

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#322]
problem is here:
```go
func key(pKey []byte, cCols []byte) []byte {
	return append(pKey, cCols...)
}
```
solution is to pre-allocate buffers for the keys. Return error when no pre-allocated buffers available

pass struct StorageCacheConf in factory arguments:
- preallocatedBuffersCount
- preallocatedBufferSize
- maxBytes

**Comment by michael-say** [comment]
problem is here:
```go
func key(pKey []byte, cCols []byte) []byte {
	return append(pKey, cCols...)
}
```

**Comment by DaniilSolovyov** [comment]
Please 
- clone this branch https://github.com/DaniilSolovyov/voedger/tree/bench
- change dir `cd ./pkg/istoragecache`
- start benchmarks `go test -bench=Benchmark_Get.* -benchmem -benchtime=10000000x`

My result is
```
goos: windows
goarch: amd64
pkg: github.com/voedger/voedger/pkg/istoragecache
cpu: 12th Gen Intel(R) Core(TM) i7-12700
Benchmark_Get_FastCache-20                                                      10000000                24.78 ns/op            0 B/op          0 allocs/op
Benchmark_Get_IStorageCache-20                                                  10000000                67.98 ns/op            8 B/op          1 allocs/op
Benchmark_Get_IStorageCache_WithoutMetrics-20                                   10000000                43.61 ns/op            8 B/op          1 allocs/op
Benchmark_Get_IStorageCache_WithoutMetrics_WithByteBufferPool-20                10000000                46.67 ns/op            0 B/op          0 allocs/op
Benchmark_Get_IStorageCache_WithoutMetrics_WithPoolAndPreAllocatedKeys-20       10000000                71.58 ns/op           45 B/op          0 allocs/op
Benchmark_Get_IStorageCache_WithoutMetrics_WithPool-20                          10000000                83.31 ns/op           16 B/op          1 allocs/op
```
- Benchmark_Get_FastCache - it is only fastcache.Get method without allocations we can not get faster speed than it   
- Benchmark_Get_IStorageCache - current implementation
- Benchmark_Get_IStorageCache_WithoutMetrics - current implementation without metrics as you see collect metrics takes a lot of time
- Benchmark_Get_IStorageCache_WithoutMetrics_WithByteBufferPool - implementation without metrics but with [valyala/bytebufferpool](https://github.com/valyala/bytebufferpool) for keys. It is just byte buffer pool without memory and size constraints
- Benchmark_Get_IStorageCache_WithoutMetrics_WithPoolAndPreAllocatedKeys - implementation without metrics but with pool of byte buffer keys the keys are pre-allocated
- Benchmark_Get_IStorageCache_WithoutMetrics_WithPool - implementation without metrics but with pool of byte buffer keys the keys are not pre-allocated

In my opinion [this function](https://github.com/voedger/voedger/blob/ae593f55ce0c737035e1a2e8d6bc52272ba0bc9b/pkg/istoragecache/impl.go#L178) is not a problem and current `cachedAppStorage` works at maximum speed

**Comment by host6** [comment]
Too complicated solution and almost no profit
