### ISSUE TITLE
Draft vrestaurant schema

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#354]
- https://github.com/voedger/voedger/tree/main/pkg/parser/example-vrestaurant
- articles, tables, orders, payments
- Namings and comments!!!
  - bill, pbill?
 - Nocode!
 - https://github.com/heeus/heeus-design/blob/main/20220414-slack-wdocs/slack-sql-syntax.md

- [dev branch](https://github.com/ivvist/voedger/blob/354-draft-vrestaurant-schema/pkg/parser/sql_example_app/vrestaurant/package.sql)

**Comment by maxim-ge** [comment]
## Naming

[Schemas Naming Convention](https://dev.heeus.io/launchpad/#!19569)

```sql
-- TYPE Order: describes data structure, retuned after executing Command Order
TYPE Order (
    ord_datetime int64,
    id_user int64
);
```

```sql
-- TYPE Order: describes data structure, retuned after executing Command Order
TYPE Order (
    OrdTimestamp datetime,
    UserID ref(User)
);
```

##Comments

Use in-place comments

## Users => POSUsers

**Comment by ivvist** [comment]
1. UserID ref(User) - ref in Type is impossible atm
2. Type Timestamp does not exist and impossible to define it.
