### ISSUE TITLE
pkg/parser: draft schema parser

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#36]
- [ ] air => example
- [ ] PRIMARY KEY
- [ ] ?;

???
```sql
TABLE MyTable(
  FieldDef1
  FieldDef2
  (
     UNIQUE ...
     PRIMARY...
  )

)

```

**Comment by maxim-ge** [comment]
```
package main

import (
	"fmt"
	"reflect"
)

type Person struct {
	Name   *string
	Age    *int
	Height *float64
}

func main() {
	// 30 := 30
	v175 := 175.
	p := Person{Name: nil, Age: nil, Height: &v175}

	v := reflect.ValueOf(p)
	t := v.Type()
	for i := 0; i < v.NumField(); i++ {
		field := v.Field(i)
		if field.Kind() == reflect.Ptr && !field.IsNil() {
			fieldName := t.Field(i).Name
			fmt.Printf("First non-nil pointer field found: %s = %v\n", fieldName, field.Interface())
			break
		}
	}
}
```

**Comment by maxim-ge** [comment]
- Use [this naming convention](https://dev.heeus.io/launchpad/#!19569)
- Use errors.Join(err1, err2)

**Comment by maxim-ge** [comment]
BasicUsage - do not test

**Comment by maxim-ge** [comment]
```sql

WORKSPACE MyWS (
  (
    Field1
    Field2
  )
  ...
)

WORKSPACE MyWS (
  DESCRIPTOR (
    Field1
    Field2
  )
  ...
)

```

**Comment by maxim-ge** [comment]
```sql

-- WITH per syntax element
  TABLE MyTable (
    DescrDef1
    DescrDef2
    WITH PRIMARY KEY ...
    WITH UNIQUE  ...
  )

-- WITH section
TABLE MyTable (
  DescrDef1
  DescrDef2
  WITH (
     PRIMARY KEY ...
     UNIQUE  ...
     COMMENT ...
     TAGS ...
  )
)
```

**Comment by michael-say** [comment]
@maxim-ge declaring comments & tags in tables using `WITH COMMENT` and `WITH TAGS` is not the best idea, because it conflicts with the way we declare them in [Commands and Queries](https://github.com/michael-say/voedger/blob/4097eb324330d59ec54b2be5e9a238c1125c6398/pkg/parser/example_app/air.sql#L66). I suggest keep comments and tags declaration either using `WITH Comment=MyComment, Tags=[Tag1, Tag2]`, or using separate declarations `COMMENT ON TABLE abc IS MyComment`, `TAG ON TABLE abc IS [Tag1, Tag2]`

**Comment by maxim-ge** [comment]
- TABLE <name> INHERITS <another table> OF <type>,...
