### ISSUE TITLE
performance: Optimize reads from bytes.Buffer

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#380]
## Problem/Motivation

[encoding/binary.Read()](https://cs.opensource.google/go/go/+/refs/tags/go1.20.5:src/encoding/binary/binary.go;l=232;drc=986b04c0f12efa1c57293f147a9e734ec71f0363) causes a lot of heap memory allocation

### binary.Read
![image](https://github.com/voedger/voedger/assets/11589750/3770b126-8b01-46c5-b7ac-b40b2ac5dad9)

### istructsmem.loadRowSysFields
![image](https://github.com/voedger/voedger/assets/11589750/af7d11e4-3919-47ce-ad3a-895c8656ce74)

### istructsmem.loadRow

![image](https://github.com/voedger/voedger/assets/11589750/237ec265-2f14-4585-8103-6d28db958857)

### See also

- «Avoid allocations in encoding/binary.Read» [#379](https://github.com/voedger/voedger/issues/379)

## Proposal

- All calls of `binary.Read()` are from `istructsmem` package. 
- All calls pass to `binary.Read()` in first parameter `*bytes.Buffer`.
- All reads can be replaced with direct encoding bytes from buffer. Bytes to convert must be taken by `bytes.Buffer.Next()`.

- Expected gain ≈4.5%, see [#379](https://github.com/voedger/voedger/issues/379)

## Technical design

- [x] Add `ReadByte()`, `ReadInt32()`, `ReadInt64()`, … functions to `istructs/internal/utils` package. General syntax:
```go
func ReadUInt××(buf *bytes.Buffer) (int××, error) {
  … // check EOF error
  return binary.BigEndian.Uint××(buf.Next(××)), nil
}
```
## Functional design

- [x] Replace in `istructsmem` package all calls of `binary.Read()` with `utils.Read×××()`

**Comment by maxim-ge** [comment]
@mail2nnv  As I understand the proposal also affects:
```
7853593622  4.37% 24.82% 14401952343  8.02%  github.com/voedger/voedger/pkg/istructsmem.loadRowSysFields
7430043683  4.14% 28.96% 27223808044 15.16%  github.com/voedger/voedger/pkg/istructsmem.loadElement
```
