### ISSUE TITLE
dynobuffers: wrong metric assumtion

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#382]
https://github.com/untillpro/dynobuffers/blob/4ed4b822719528d9f90df364ad0fa9d8451645fe/dynostorage.go#L200C10-L200C10 - count may not reflect the reality since sync.Pool might be cleaned in background

**Comment by host6** [comment]
actually this metric shows the difference between amounts of `NewBuffer()` and `Release()` calls. I.e. != 0 -> something is wrong on the code level. `sync.Pool` behaviour has no sence here.
