### ISSUE TITLE
panic: test timed out after 10m0s

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#387]
**Describe the bug**

https://github.com/voedger/voedger/actions/runs/5499064472/jobs/10020994906

- This is not the same bug as mentioned here https://github.com/voedger/voedger/issues/359
  - https://github.com/voedger/voedger/blob/e7b74641ab1715d61ce3db454cd306ba7cf543be/pkg/sys/it/impl_n10n_test.go#L20
  - https://github.com/voedger/voedger/blob/f678465ae6415d1667c3ad2b46249875df40d229/pkg/vit/impl_test.go#L124

**Comment by host6** [comment]
duplicate of #359

**Comment by host6** [comment]
Not happens anymore. Most likely fixed by solution of #359
