### ISSUE TITLE
Rename Air Workspaces

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#468]
# Motivation
Workspace name and Workspace Descriptor must have different names

# Technical Design

- Workspaces:
  - Restaurant -> RestaurantWS
  - Reseller -> ResellerWS
  - Resellers -> ResellersWS
  - UntillPayments -> UntillPaymentsWS
- Rename QNames
- update client apps
- update create workspace function

**Comment by host6** [comment]
https://github.com/untillpro/airs-bp3/pull/588

**Comment by host6** [comment]
Restaurant -> RestaurantWS is done in https://github.com/untillpro/airs-bp3/pull/588, the rest of items are not defined yet, so just will be created with new correct names
