### ISSUE TITLE
Parser: some additional features

### ISSUE THREAD

**Issue by ivvist** [voedger/voedger#472]
1. Add built-in types "timestamp"(int64) and "currency"(int64)
2. Add comment before Table "--My comment" in AST as if it's described with Comment="My comment"
3. If Type struct is defined. I should be able to Add it as fieldset to Table, like

```
TYPE MyType(
   f1 int,
   f2 int
)

TABLE MyTable(
   MyType
)
```
Instead of 

```
TABLE MyTable Of MyType
```
4. ABSTRACT Table - should be allowed to restrict creating abstarct tables.

**Comment by michael-say** [comment]
Decomposed to:

- #483 
- #484 
- #485

**Comment by michael-say** [comment]
all done except (4) which is moved here: #510
