### ISSUE TITLE
PR title and comments

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#497]
## Requirements

- Pull request title: #[Issue number] [Issue name]
- Pull request description: Resolves #[Issue number] [Issue name]
  - Rationale: linking-a-pull-request-to-an-issue-using-a-keyword
- Comment in PR Commit: #[Issue number] [Issue name] (#[Pull request number])

## Context

- https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

## Misc

https://github.com/voedger/voedger/commit/15ef848eecdc1950a6eba71732991012d509be18
- No comments at all
- Resolves: <issue-name> # <issue-number> (# <PR number>)

![image](https://github.com/voedger/voedger/assets/11589750/756d920d-51ee-4833-b35a-2dede86cdff2)

**Comment by ivvist** [comment]
Pull request title: Resolves issue [Issue name] #[Issue number]
Pull request description: Resolves #[Issue number] [Issue name]
Comment in PR Commit: Resolves issue #[Issue number] [Issue name] (#[Pull request number])

**Comment by ivvist** [comment]
Pull request title: Resolves issue [Issue name] #[Issue number]
Pull request description: Resolves #[Issue number] [Issue name]
Comment in PR Commit: Resolves issue #[Issue number] [Issue name] (#[Pull request number])

**Comment by maxim-ge** [comment]
![image](https://github.com/voedger/voedger/assets/11589750/44edebc1-0f18-4d8a-9fe9-f4a7d94fd9a7)

**Comment by ivvist** [comment]
Pull request title:  #[Issue number] [Issue name]
Pull request description: Resolves #[Issue number] [Issue name]
Comment in PR Commit: #[Issue number] [Issue name] #[Pull request number]
