### ISSUE TITLE
Cache candidates performance investigation

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#504]
## Motivation

To justify the choice of implementation of the [object cache](https://github.com/voedger/voedger/issues/455), it is necessary to investigate the performance of various implementations of the cache.

## Cache implementation to investigate

1. [Ristretto, 4.8K stars](https://github.com/dgraph-io/ristretto)
1. [hashicorp/golang-lru, 3.6K starts](https://github.com/hashicorp/golang-lru)
1. [gcache, 2.4K stars](https://github.com/bluele/gcache)
1. [theine-go, 103 stars](https://github.com/Yiling-J/theine-go)
1. [imcache, 66 stars](https://github.com/erni27/imcache)
1. [floatdrop, 19 stars](https://github.com/floatdrop/lru)

- theine-go seems as a techincal leader, but not popular (yet?)
- theine-go [claims](https://github.com/dgraph-io/ristretto/issues/336) that Ristretto hits ration is very low (???). Strange that the Ristretto Team has not answered it yet 
- ristretto dies NOT provide generic interface
- theine-go and hashicorp/golang-lru DOES provide generic interface
- hashicorp/golang-lru seems as a preferrable solution (generic + popular)
  -  lru, since it is not clear how to handle evict event in mru version

## Proposal

An exploratory object cache prototype is created in a separate `voedger/inv-go` repository. A prototype, compared to a fully functional cache, should not have a mechanism for automating references and destroying objects, but should provide easy switching of implementation between different candidates.

The following quantitative and qualitative characteristics are subject to assessment:
- **support for generics**
- peak memory usage
- time of a single operation to store the value in the cache:
   - with sequential access
   - with parallel access
- time of a single operation to get the value from the cache
   - with sequential access
   - with parallel access.

## Results

<details><summary>Bench results</summary>
<p>

[bench.md](https://github.com/voedger/inv-go/blob/main/20230724-objcache/results/bench.md)

</p>
</details> 

<details><summary>Graphics</summary>
<p>

![image](https://github.com/voedger/voedger/assets/36446176/88e3812d-14ad-45f1-b2c7-9cd41f7a66fe)

![image](https://github.com/voedger/voedger/assets/36446176/9ea2d8cf-6fb9-4cd2-b83a-60eca451cb08)

</p>
</details> 

## Conclusions

- `Ristretto` is not suitable as it does not support generics
- `Theine-go` is not suitable, as it shows unacceptable peak memory usage
- the three remaining candidates (`hashicorp`, `imcache` and `floatdrop`) show approximately the same results, but `hashicorp` should be preferred for the following reasons:

1. Great popularity (3.6K stars versus 66 and 19 respectively)
2. Slightly better cache stacking speed (~10-15%)

Choice: **[hashicorp/golang-lru, 3.6K starts](https://github.com/hashicorp/golang-lru)**

**Comment by Yiling-J** [comment]
@mail2nnv hi, Theine author here. I want to know more about "unacceptable peak memory usage", but the benchmark repo and result links are invalid. Could you please fix them or tell me the right one? So I can take look. Recently Vitess has made a decision to use theine as its plan cache, if there is some serious performance issues, i need to take a look and try to fix.

**Comment by mail2nnv** [comment]
Apparently, links to the investigation lead to a private repository.

I made a [public repository](https://github.com/mail2nnv/objcache) in which I copied this.

**Comment by Yiling-J** [comment]
@mail2nnv take a look the bench code and i have a question: [bench_test.go](https://github.com/mail2nnv/objcache/blob/5b361447f156efc2990322a405c1cfdcec92cfca/bench_test.go#L58C10-L58C10), why init a new cache in each run? I tried create a new cache globally and run your benchmark again, the results is different.

**Comment by mail2nnv** [comment]
@Yiling-J This is, in a simplified form, the architecture of the system for which the study was carried out - event sources are each served in their own workspaces, each workspace has its own cache.

**Comment by Yiling-J** [comment]
@mail2nnv I think the benchmarks should not include setup cost, because setups are usually done when server/services initialized. Is your architecture serverless? To me the only case match current benchmark is using aws lambda, which has to initialized in each run. If your workspace count are limited and not that much, i would suggest initializing several cache first and pick random one is each run.

**Comment by maxim-ge** [comment]
@Yiling-J good point👍, we will investigate it. If you are right we will change our conclusion, do not worry.

**Comment by mail2nnv** [comment]
I agree that moving cache initialization can reduce test execution time (performance gain), but I don't see how it will reduce memory usage.

We cannot reduce the number of caches. I already wrote that this is a reflection of the system architecture in a simplified form. 

<details><summary>The architecture can be described in more detail as follows</summary>
<p>
Workspaces are processed in command processors. Several different workspaces can be processed by one processor, but no workspace can be processed by two processors at once. That is, each workspace is assigned to a specific command processor according to some balancing algorithm. Thus, workspaces naturally develop single points of query processing, which are the preferred caching points. We don't want to make the cache larger by splitting it across multiple processors, as this will result in poor caching efficiency for slow workspaces with low event traffic.
</p>
</details>

**Comment by Yiling-J** [comment]
@mail2nnv The high memory usage is expected, because Theine will preallocate **a map for data, 2 LRU for policy and N small LRU for proactive expiration**. Theine will also start 2 goroutines for eviction and expiration. That's a lot, so if you init a Theine instance in each run, all these have to be created again. If GC is not fast, the memory usage will be high.

On the other hand, HashiCorp LRU use a map and a list, both are not preallocated, and no extra goroutines.

I think if you have thousands of workspaces and they need to be cached separately, Theine is not good choice.
