### ISSUE TITLE
SQL: datatype varchar

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#522]
- size - in runes
- max size is 1024, controlled by parser
- default size is 255
- regexp checks

```sql
CRATE TABLE MYTABLE(
  Zip varchar(10) CHECK '^[0-9]{1,10}$',
)
```

depends on #581

**Comment by mail2nnv** [comment]
To specify both lengths (main & max) may be used extended syntax like:

```
CRATE TABLE MYTABLE(
  Zip varchar(4,10) CHECK '^[0-9]{4,10}$',
)
```
