### ISSUE TITLE
Unable to erase string field

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#54]
**Describe the bug**
It is impossible to erase (at least) string field with CUD. Sending empty string with CUD does nothing with the existing value.

**To Reproduce**
1. Store some value in existing string field
2. Try to erase it by sending empty value in CUD

**Expected behavior**
A field value is updated to empty value

**Current behavior**
A field value is not updated

**Comment by host6** [comment]
https://github.com/untillpro/airs-bp3/commit/dfbb9bfb5489c409edbde3b0873a53d8e4f680c7
