### ISSUE TITLE
datatype text -> varchar(n) in voedger schemas

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#603]
See #522

**Comment by host6** [comment]
- ChildWorkspace.WSKindInitializationData, WorkspaceID.WSKindInitializationData, WorkspaceDescriptor.WSKindInitializationData + TemplateParams?
- WorkspaceDescriptor.CreateError, WorkspaceDescriptor.InitError, ChildWorkspace.WSError - what if the error will be longer than 1024 bytes? cut + log? 
-
