### ISSUE TITLE
AppDef compatibility tool

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#617]
## Requirements

A tool compares two versions of AppDef and check their compatibility. Schemas are compatible when all following conditions are met:
- All QNames from ast1 exist in the new ast2
- Fields set (except view keys)
  - order and type change denied
  - ~size decrease denied~
    - size decrease allowed because it is still able to read old long values
  - removal denied
  - existing tables, keys, types etc:
    - append non-required only only, no insert
    - become required denied
  - new tables, keys, types etc - no checks
- In Views:
  - Keys, Value: change denied
  - Key fields: any change denied
- Tables:
  - parent/child relationships not changed from ast1 to ast2
  - inheritance is not changed (e.g. CDoc->WDoc, non-singleton->singleton etc)
  - unique field add denied
- Projectors:
  - SYNC property not changed from ast1 to ast2
  - ON, STATE, INTENT - may change from ast1 to ast2!
- Commands:
  - Args, UnloggedArgs change denied
  - Result change allowed
- Workspaces:
  - new version can not become abstract
  - inheritance is not changed

### Context

- https://github.com/voedger/voedger/issues/167

## Design

ref. [README-compat.md ](https://github.com/voedger/voedger/blob/main/pkg/appdefcompat/README.md)
- [Development version](https://github.com/anurmanov/voedger/blob/617-parser-package-ast-compatibility-tool-1/pkg/appdefcompat/README.md)

**Comment by michael-say** [comment]
@anurmanov I've updated the Functionad Design section

**Comment by anurmanov** [comment]
@michael-say got it

**Comment by maxim-ge** [comment]
@michael-say It is necessary to check the whole application, seems it checks onle one package? May be we need two functions, CheckPackageBackwardCompatibility, CheckAppBackwardCompatibility

**Comment by host6** [comment]
@michael-say, why https://dev.heeus.io/launchpad/#!17990 is not used? e.g. a CDoc become a singleton should be denied

**Comment by michael-say** [comment]
> @michael-say, why https://dev.heeus.io/launchpad/#!17990 is not used? e.g. a CDoc become a singleton should be denied

@host6 I thought you'll going to merge info into this task?

**Comment by michael-say** [comment]
> @michael-say It is necessary to check the whole application, seems it checks only one package? May be we need two functions, CheckPackageBackwardCompatibility, CheckAppBackwardCompatibility?

Indeed, there will be an additional function when [AppSchemaAST](#658 ) is implemented

**Comment by maxim-ge** [comment]
## Techical design

```
rules map[stmtTypeName]rule

type struct rule 
  ordered
  appendOnly
  
func validateStm(old, new)
   innerStmtsNew map[stmtTypeName][]Stmt
   innerStmtsOld map[stmtTypeName][]Stmt
   innerStmtsNew = gatherStmts(new)
   innerStmtsOld= gatherStmts(old)
   for each stmtTypeName, stmts in innerStmts 
     rule = rules[stmtTypeName]
     validateCollection(rule, innerStmtsNew, innerStmtsOld)
     


```

**Comment by maxim-ge** [comment]
To be continued in #736
