### ISSUE TITLE
Automatically link issue to milestone (on issue close)

### ISSUE THREAD

**Issue by ivvist** [voedger/voedger#645]
## Functional Design

- When voedger issue is closed issues is automatically linked to the active Voedger milestone
- There must be one and only one active Voedger milestone
  - Issue is re-opened if this is not true

## Technical Design

- New [Workflow action on Issue close event](https://github.com/voedger/voedger/blob/main/.github/workflows/linkIssue.yml) added.
It's triggered when an Issue is closed by any method. 

Done

**Comment by ivvist** [comment]
gh api repos/org/repo/milestones --jq ".[] | .title"

**Comment by maxim-ge** [comment]
Use latest milestone if current is not found
