### ISSUE TITLE
Go Vulnerability Management

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#652]
## Problem/Motivation/Requirement

- Use Vulnerability Management tool
- There should be a way to avoid some problems
   -  Normally if any problem occurs build must fail, but we need to avoid some problems
- Run in the "Daily tests" suite.

## Context

**Vulnerability Management tool**
https://go.dev/security/vuln/
- $ go install golang.org/x/vuln/cmd/govulncheck@latest
- $ govulncheck ./...

## Functional Design

- Vulnerability Management tool is run during [Daily Test Suite](https://github.com/voedger/voedger/blob/main/.github/workflows/ci-full.yml) in case if all tests pass fine
- Daily Test Suite fails if any vulnerability found

### Configuration
- File .govulnc-exclude is in root of voedger/voedger repository. 
It can contain codes to be excluded from Vulnerability checking.
Example:
GO-2023-1987
GO-2023-2041

## Technical Design
Vulnerability Management tool is run by [seperate github action](https://github.com/voedger/voedger/blob/main/.github/workflows/ci-vulncheck.yml) 
The action is run from [Daily Test Suite](https://github.com/voedger/voedger/blob/dcd87ddfbe47a426a2708110303753c497f46f63/.github/workflows/ci-full.yml#L21C27-L21C27) after successfull testing.

**Comment by ivvist** [comment]
Problem: There is no support for silencing vulnerability findings. See https://go.dev/issue/61211 for updates.
https://pkg.go.dev/golang.org/x/vuln/cmd/govulncheck

**Comment by maxim-ge** [comment]
Add a way to exclude vulnerabilities using bash script

```
cat o | grep "Vulnerability #" ...
...
```

**Comment by ivvist** [comment]
Done.
