### ISSUE TITLE
Validate record non-raw references

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#663]
## Principles

- Sync projector stores new IDs and QNames from CUDs and `Args` 
- `Args` and `UnloggedArgs` are checked by the command processor before cmd exec
- resulting CUDs are checked by the validator after cmd exec
- any ref field value is checked for existence and for target record's QName allowness
- non-ref `RecordID` fields are not checked
- need to run the projector in async mode first to fill the view in Alpha, RC and Release, then run it in the sync mode only

## Functional Design
- the client calls a command with a non-raw ref field in `Args`, `UnloggedArgs` or CUDs
  - reference target does not exist -> `400 bad request` + `referential integrity violation: record ID <ID> referenced by <doc.field> does not exist`
  - target record's QName is not allowed -> `400 bad request` + `referential integrity violation: record ID <ID> referenced by <doc.field> is of QName <refQname> whereas <set of allowed Qnames> QNames are only allowed`
- airs-bp3 is run with `--rebuild-registry` cmd line that will run `p.sys.Registry` in async mode so that all existing records will be written to the registry. The entire log will be processed by `ap.sys.Registry`, then this flag must be removed

## Technical Design
```sql
VIEW Registry (
  IDHi int64 NOT NULL,
  ID ref NOT NULL,
  WLogOffset int64 NOT NULL,
  QName qname NOT NULL,
  PRIMARY KEY ((IDHi), ID)
) AS RESULT OF RegistryProjector;
```
-  `IDHi = ID>>18`
- `p.sys.RegistryProjector` fills the `Registry` view after cmd exec
  - for each CUD and `Args`
    - write `WLogOffset` and `QName` of the record under ((IDHi), ID) key to the view
    - write the same for each element recursively
  - note: `UnloggedArgs` will not be saved -> nothing to store in `Registry`
  - note: historical events will not be processed by the projector to prevent Ref Integrity Violation errors on recover those events
- `checkArgsRefIntegrity` command processor operator checks ref integrity for fields of `Args` and `UnloggedArgs` before cmd exec:
  - `builtin.CheckRefIntegrity(Args)` + `builtin.CheckRefIntegrity(UnloggedArgs)` called
- `sys.RefIntegrityValidator` CUD validator checks ref integrity of CUDs after cmd exec
  - `builtin.CheckRefIntegrity(cudRow)` is called
- `builtin.CheckRefIntegrity(IRowReader)` returns `builting.ErrRefIntegrityViolation` error if the ref integrity is broken for any ref field of `IRowReader`
  - ref field value is `NullRecordID` or is raw -> skip
  - look for the target ID in the `Registry` view
  - found -> check QName of the target rec: not allowed -> error
  - not found -> error
### Partition size 
- value size is  8 (ID) + 2(QNameID) + 8(WLogOffset) = 18 bytes
- 2^18*18 = 4 718 592 bytes

**Comment by mail2nnv** [comment]
# Questions
- Is the registry supposed to store all IDs or only IDs of `ODoc/ORecord`s? 
- If all IDs, then there is no way to delete (deactivate) an entry from the registry! It is necessary to add `IsActive bool` to the value. 
- If not only `ODoc/ORecord`s IDs, how is it supposed to check references to untyped (or typed by different struct types) records? Both on the repository by reading the whole record and on the registry? How efficient/ugly is this?

**Comment by host6** [comment]
> # Questions
> * Is the registry supposed to store all IDs or only IDs of `ODoc/ORecord`s?
decided to store all IDs
> * If all IDs, then there is no way to delete (deactivate) an entry from the registry! It is necessary to add `IsActive bool` to the value.
not necessary to store active\inactive state. I create a record that have a link to an existing inactive record - what the problem
