### ISSUE TITLE
vSQL: APPLICATION statement

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#665]
# Motivation
- ref. #658 :

# Principles
- When merging package schemas into `AppSchemaAST`, it is required that exactly one package contains `APPLICATION` statement describing the app: it's name and packages
- `SCHEMA` definition not needed anymore. 
- Package names in QNames of the application are defined by `USE` statements of the `APPLICATION` definition

# Functional Design
1) package may contain `APPLICATION` statement:
```sql
IMPORT SCHEMA 'github.com/untillpro/untill' AS air;
IMPORT SCHEMA 'github.com/untillpro/airsbp';

-- Only one APPLICATION statement allowed per package
APPLICATION bp3 (
  -- "sys" is always used in any application
  USE air;  -- name or alias. This actually identifies package in QNames of the app
  USE airsbp; 
)
```

3) `pkg/parser/provide.go`
```go
// BuildPackageSchema merges File Schema ASTs into Package Schema AST.
// Performs package-level semantic analysis
func BuildPackageSchema(qualifiedPackageName string, asts []*FileSchemaAST) (*PackageSchemaAST, error) {
	return mergeFileSchemaASTsImpl(qualifiedPackageName, asts)
}

// Application-level semantic analysis (e.g. cross-package references)
// Exactly one package contain APPLICATION definition
func BuildAppSchema(packages []*PackageSchemaAST) (*AppSchemaAST, error) {
	return mergePackageSchemasImpl(packages)
}

func BuildAppDefs(appSchema *AppSchemaAST, builder appdef.IAppDefBuilder) error {
	return buildAppDefs(appSchema, builder)
}
```

# Tech Design
- `BuildAppSchema`:
  - Finds `APPLICATION` statement (exactly one must be defined) in the list of packages provided
  - Initlaizes package names for using in the QNames of application packages
  - Performs application-level semantic-analysis:
    - cross-package references
    - the package name for the "main" package, which contains `APPLICATION` statement, is always set automatically (e.g. "github.com/untillpro/airsbp3/main" -> "main"), so there must be a check that no package USEd with the name of "main" package

**Comment by michael-say** [comment]
@host6 after [removing](https://github.com/michael-say/voedger/commit/ecdb4b4ed9c1b58ca78207bef1d35039f73e9a86) `SCHEMA` statements from SQLs in `sys` package and adding APPLICATION in `schemasSimpleApp.sql` and `schemasEmptyApp.sql`, [TestBug_QueryProcessorMustStopOnClientDisconnect](https://github.com/voedger/voedger/blob/ed4d22c398dc0748f943510ee7be473e03db5b5a/pkg/sys/it/bug_test.go#L54) fails with "application not defined". 
It happens because [parser.BuildAppSchema](https://github.com/voedger/voedger/blob/ed4d22c398dc0748f943510ee7be473e03db5b5a/pkg/vvm/impl_builder.go#L47) is provided with the list of packages containing only `sys` package. The package `sys` doesn't contain `APPLICATION` by design, it only used as a part of packages. It seems we should provide sime dummy application for this case. Please take a look.

**Comment by host6** [comment]
> @host6 after [removing](https://github.com/michael-say/voedger/commit/ecdb4b4ed9c1b58ca78207bef1d35039f73e9a86) `SCHEMA` statements from SQLs in `sys` package and adding APPLICATION in `schemasSimpleApp.sql` and `schemasEmptyApp.sql`, [TestBug_QueryProcessorMustStopOnClientDisconnect](https://github.com/voedger/voedger/blob/ed4d22c398dc0748f943510ee7be473e03db5b5a/pkg/sys/it/bug_test.go#L54) fails with "application not defined". It happens because [parser.BuildAppSchema](https://github.com/voedger/voedger/blob/ed4d22c398dc0748f943510ee7be473e03db5b5a/pkg/vvm/impl_builder.go#L47) is provided with the list of packages containing only `sys` package. The package `sys` doesn't contain `APPLICATION` by design, it only used as a part of packages. It seems we should provide sime dummy application for this case. Please take a look.

https://github.com/michael-say/voedger/pull/1
