### ISSUE TITLE
implement `registry` package

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#672]
# Motivation
`c.sys.CreateLogin` must exist in `sys/registry` app only. To implement that in sql need to shoot off `CreateLogin` functionality in a separate package `registry` and use it in `sys/registry` app only.

# Tech design
- migrate to `registry` package:
  - `cdoc.sys.Login`
  - `view.sys.LoginIDx`
  - `sys.CreateLogin`, `obj.sys.CreateLoginParams`, `obj.sys.CreateLoginUnloggedParams`
  - `p.sys.ProjectorLoginIdx`
  - `c.sys.ResetPasswordByEmail`, `obj.sys.ResetPasswordByEmailParams`, `obj.sys.ResetPasswordByEmailUnloggedParams`
  - `q.sys.InitiateRestPasswordByEmail`, `obj.sys.InitiateResetPasswordByEmailParams`, `obj.sys.InitiateResetPasswordByEmailResult`
  - `q.sys.IssueVerifiedValueTokenForResetPassword`, `obj.sys.IssueVerifiedValueTokenForResetPasswordParams`, `obj.sys.IssueVerifiedValueTokenForResetPasswordResult`
- `c.sys.CreateWorkspaceID`, `c.sys.CreateWorkspace`,  `cdoc.sys.WorkspaceID`
  - has `OwnerQName qname` field. Create a login -> `registry.Login` QName will be written in this field -> error because there is no such cdoc in the target app. Solution - deprecate `OwnerQName qname`  field and use `OwnerQName2 text` field from now on

**Comment by host6** [comment]
renamed: `cdoc.sys.Login` -> `cdoc.registry.Login` in `untill/airs-bp` app
