### ISSUE TITLE
Validate required field with zero-values

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#682]
## Problem

The field description specifies that it is required, but the user has filled it with a zero value.

**Now, in current architecture**
Only field values of `DataKind_RecordID` type are validated for non-zero values.

[Exists code](https://github.com/voedger/voedger/blob/ce7b1792dcf0d52ccf2e46a415fcf81626f0c001/pkg/istructsmem/validation.go#L179)

<details><summary>Expanded data kind switch</summary>

<p>

``` golang
// Validates specified row
func (v *validator) validRow(row *rowType) (err error) {
  v.typ.(appdef.IFields).Fields(
    func(f appdef.IField) {
      if f.Required() {
        if !row.HasValue(f.Name()) {
          err = errors.Join(err,
            validateErrorf(ECode_EmptyData, "%s misses field «%s» required for type «%v»: %w", v.entName(row), f.Name(), v.typ.QName(), ErrNameNotFound))
          return
        }
        if !f.IsSys() {
          switch f.DataKind() {
          case appdef.DataKind_RecordID:
            if row.AsRecordID(f.Name()) == istructs.NullRecordID {
              err = errors.Join(err,
                validateErrorf(ECode_InvalidRefRecordID, "%s required ref field «%s» has NullRecordID value: %w", v.entName(row), f.Name(), ErrWrongRecordID))
              }
            }
          }
        }
      })

  return err
}
```

</p>
</details> 

- Problem (warm): Are fields of other types (Numeric, String & Bytes, `DataKind_QName`, ...) required to be validated similarly?

**Comment by host6** [comment]
Not required because the initial problem is related to ref fields only: required ref RecordID field is zero -> schema-related validation passes (zero is not nil -> ok) but SalesMetrics projector compared that ref field to NullRecordID which is zero as well. Collision: has value but NullRecordID.
Let's consider zero values for other types as valid not null values

**Comment by mail2nnv** [comment]
The problem is in one of two cases:
1. in the new record, fill the required field with zero (empty string), and the validator should throw an error, or
2. in the edited record, clear the required field (by writing a zero/empty string), and the validator should throw an error.

Both of the above cases can be solved by imposing a constraint on the field (or on the data type in the field), `MinLength: 1` for a string or `MinExcl: 0` for a number
