### ISSUE TITLE
Using sys.Result for sending results from QP

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#732]
## Problem
Now, developer provide QueryFunction excutable functions using `IResources`. To let the procedure return results, this function  is provided with a callback for passing the result data, which is then sent through the bus. This doesn't fit into "extensions" design.

## Concepts
QueryFunction extensions must be able to provide results using Intents, just like any other types of extensions.

## Functional Design
Result is sent by creating `NewValue` intents in `sys.Result` storage, as many times as needed:
```go
func myQuery {
	args := ext.MustGetValue(ext.KeyBuilder(ext.Args, ext.NullEntity))
	arg := args.GetAsValue(0)
        // ....
        
        
	// Some query function extension    
        ext.ReadValues(viewPartialKey, func(key ext.TKey, value ext.TValue) {
            /*
                In QueryProcessor "Result" storage works differently:
                NewValue, created in ext.Result, will be sent through bus: 
                    - every time a new value is created over the old one;
                    - when the execution is over.
            */
            result := ext.NewValue(ext.KeyBuilder(ext.Result))  
            result.PutString("name", value.AsString("FullName"))
            result.PutInt32("age", customer.AsInt32("Age"))
        })
}
```

## Technical Design
- Rename storage `CmdResult` -> `Result` 
- Storage works differently for CP and QP: for QP It sends the Intent to the bus when:
    - extension requests an NewValue intent and there's already previous intent 
    - on flushing bundles

**Comment by host6** [comment]
done already
