### ISSUE TITLE
sql: projector on any

### ISSUE THREAD

**Issue by host6** [voedger/voedger#752]
## Problem

**Now, in current architecture**
it is required to specify set of docs the projector will work on

- Problem (warm): impossible to specify a projector that should work on an any document, e.g. `sys.RecordsRegistryProjector` (#663 )

**Describe the solution you'd like**
- `SYNC PROJECTOR MyProj ON(any) INTENTS...`
- `SYNC PROJECTOR MyProj ON() INTENTS...`
- `SYNC PROJECTOR myProj INTENTS...`
- etc

**Comment by michael-say** [comment]
@host6 is ANY mean any CDoc, WDoc or ODoc?
Suggested syntax:
```sql
PROJECTOR RecordsRegistryProjector
            AFTER INSERT OR UPDATE ON ANY
...
```

**Comment by host6** [comment]
@michael-say, yes: ANY - any *Doc. Suggested syntax is ok for me. I assume that in this case the projector will be actually created with the `MatchFunc` func that will always return true.

**Comment by michael-say** [comment]
```sql
PROJECTOR RecordsRegistryProjector
            AFTER INSERT OR UPDATE ON (CDoc, WDoc)  -- When ABSTRACT, then triggered by any nested table
```
