### ISSUE TITLE
vSQL: WDoc singletone

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#761]
## Motivation
- Not possible specify WDoc singletone in vSQL
- https://dev.untill.com/projects/#!661642

## Functional Design
sys package:
```sql
ABSTRACT TABLE CSingleton INHERITS CDoc();
ABSTRACT TABLE WSingleton INHERITS CDoc();
```

```[tasklist]
### Tasks
- [ ] https://github.com/voedger/voedger/issues/762
```

**Comment by maxim-ge** [comment]
@michael-say I incline to the conclusion that tables like NextNumbers  should CDoc's...

**Comment by michael-say** [comment]
decided not to implement
