### ISSUE TITLE
SchemaCache => IAppDef

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#77]
### Naming:
- [x] package `schemas` => `appdef`
  - [x] interface `SchemaCache` => `IAppDef`
    - [x] func `Add()` => `AddStruct()`. Panics if kind is not struct, e.g. view, command, query…
  - [x] interface `SchemaCacheBuilder` => `IAppDefBuilder`
  - [x] interface `Schema` => `IDef`
  - [x] interface `SchemaBuilder` => `IDefBuilder`
  - [x]  type `SchemaKind` => `DefKind` + constants
  - [x]  interface `ViewBuilder` => `IViewBuilder`
  - [x]  interface `Field` => `IField`
  - [x]  interface `Container` => `IContainer`

**Comment by mail2nnv** [comment]
PR: https://github.com/voedger/voedger/pull/95
