### ISSUE TITLE
Implement `bp3 baseline_schemas`

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#777]
Implement `schemas baseline_schemas <folder>`as described [here](https://github.com/voedger/voedger/issues/646)
```[tasklist]
### Tasks
- [x] Implement schemas content exporting in voedger
- [x] Implement baseline_schemas cmd in bp3
```

**Comment by host6** [comment]
- use `cobrau` in bp3
  - no commands -> all should work like before
  - `schemas` cmd is provided -> only `export` and `testcompat` subcommands must be available
