### ISSUE TITLE
Support QNameAny as function result

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#858]
# Motivation 
#839 

# Functional Design
Possibility to specify `QNameANY` as a Query Function result

# Technical design

To avoid cyrcular package reference constant `QNameAny` has been moved from `istructs` to `appdef` package.

**Comment by mail2nnv** [comment]
A deficiency in this task has been identified, formalized by a [separate task #922](https://github.com/voedger/voedger/issues/922)
