### ISSUE TITLE
perftest: update dashboard (use also metrics with voedger prefix)

### ISSUE THREAD

**Issue by michael-say** [voedger/voedger#891]
The metric names [were updated](https://github.com/voedger/voedger/issues/884). Please update perftest dashboards

**Comment by michael-say** [comment]
See also: #892 ([performance dashboard](https://github.com/untillpro/airs-dc/tree/main/grafana-dashboards) in GitHub)

**Comment by AlekseiPonomarev** [comment]
Perftest dashboard updated. Now use "voedger" prefix.
