### ISSUE TITLE
A&D: AppPartitions & Engines

### ISSUE THREAD

**Issue by maxim-ge** [voedger/voedger#943]
## Design
- apppartsctl.New() // Add Engine Factories parameter
- README.md
  - [Processors](https://github.com/michael-say/voedger/tree/943-ad-apppartitions-engines/design#processors)
  - [Borrow IAppPartition](https://github.com/michael-say/voedger/tree/943-ad-apppartitions-engines/design#borrow-iapppartition)
  - [Construct Pools of Extension Engines](https://github.com/michael-say/voedger/tree/943-ad-apppartitions-engines/design#construct-pools-of-extension-engines)
  - [Execute Extensions](https://github.com/michael-say/voedger/tree/943-ad-apppartitions-engines/design#execute-extentions)

## See Also

- #797

**Comment by michael-say** [comment]
Completed with #1066
