### ISSUE TITLE
Uniques to Def

### ISSUE THREAD

**Issue by mail2nnv** [voedger/voedger#98]
## Now:
Uniques described in `istructsmem` package. But uniques is a part of structures (docs, records …).

### Create new uniques in `appdef` package
- [x] Add to `IDefBuilder` interface new member `AddUnique(name string, fields []string)`
- [x] Add to `IDef` interface new members:
  - [x] `UniqueCount() int`,
  - [x] `UniqueByID(id UniqueID) IUnique`
  - [x] `UniqueByName(name string) IUnique`
  - [x] `Uniques(func (IUnique))`

- [x] new `IUnique` interface:
  - [x] `Name() string`
  - [x] `Fields() []IField`
  - [x] `ID() UniqueID` uint64 based identifier, see [tech.design](https://github.com/voedger/voedger/issues/98#:~:text=Unique%20identification)
  
### Deprecate old uniques from `istructs` packages
- [x]  `istructs.IAppStructs.Uniques()` **must be deprecated** and must not be used anymore (// Deprecated: + linters)
- [x]  `istructs.IUnique` must be only one per entity (panic, tests must be refactored)
- [x]  `istructs.IUnique`  must contain only one field (panic, tests must be refactored)
- [x]  `appdef.IDef.Uniques()` **must be used for NEW uniques** @host6

## Technical design: 

**Unique identification**
Unique has `ID` identifier. 

During `istructmem.AppStruct()` preparation: 
- IDs for existing uniques reads from storage from internal `uniques` system view
- if new uniques exists, then 
  - new IDs are generates and assigns to
  - internal `uniques` system view updates to storage.

Storage key: 
- PK = ViewID + ViewVersion, 
- CC = definition QNameID  + field names pipe-separated concatenation.

Internal `uniques` system view implemented in `istructsmem/internal/uniques` package.  
- [x] This must provide new `func PrepareAppDefUniqueIDs()`.

## Functional design:
- Uniques are added after fields. Panic if some unknown field passed to new unique.
- Unique name may be omitted. In this case a default unique name must be used, e.g. `tableUnique01`, where: `table` is structure entity name, `01` is unique ordered number for structure.
- The order of the fields in unique does not matter. Panic if unique duplicated.
- If some specific unique [`a`, `b`, `c`] overlaps with a more general unique [`a`, `b`], then the validation should return an error.
- `IUnique.Fields()` returns fields in alphabetical order.

**istructs.IAppStructs.Uniques() is deprecated, use appdef.IDef.Uniques()**

- [x] During application prepare must call new `uniques.PrepareAppDefUniqueIDs()`
- [x] CUD validation in airs-bp3 projectors must use new uniques @host6
- [x] Package `istructsmem/descr` must describe new uniques

**Comment by maxim-ge** [comment]
- All items from "Techical design" are important for users of Uniques feature, so they should be in "Functional design"
- "Additional" section is an example of "Technical design"

**Comment by mail2nnv** [comment]
> * All items from "Techical design" are important for users of Uniques feature, so they should be in "Functional design"
> * "Additional" section is an example of "Technical design"

OK

**Comment by maxim-ge** [comment]
- Unique is deprecated
- Unique must be only one per entity
- Unique must not be used anymore
- Unique2 must be used

**Comment by mail2nnv** [comment]
PR[#118](https://github.com/voedger/voedger/pull/118)
